chore: Provide "real" ReferenceAssemblies for net11
The **Tests - Unit Tests > Run > Run unit tests** job is failing,
and one of the reported errors is:

	Test method Uno.UI.SourceGenerators.Tests.DependencyObjectGeneratorTests.Given_DependencyObjectGenerator.TestNested threw exception:
	System.InvalidOperationException: Mismatch between number of diagnostics returned, expected "0" actual "3"

	Diagnostics:
	// error CS1705: Assembly 'Uno' with identity 'Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' uses 'System.Runtime, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
	DiagnosticResult.CompilerError("CS1705").WithArguments("Uno", "Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null", "System.Runtime, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", "System.Runtime", "System.Runtime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"),
	…

The cause of the problem is that `_Dotnet.Current` is returning
reference assemblies for *.NET 10*, not .NET 11, largely because the
[Microsoft.CodeAnalysis.Analyzer.Testing NuGet package][0] doesn't
contain an entry for .NET 11, and presumably won't until *after* the
release of .NET 11 in 2026-November.

What do we do instead?

"Fake it 'til you make it": the definition of
[`ReferenceAssemblies.Net100`][1] is concise and straightforward;
copy it, updating for .NET 11.  Do the same for .NET 11 Android.

[0]: https://www.nuget.org/packages/Microsoft.CodeAnalysis.Analyzer.Testing
[1]: ttps://github.com/dotnet/roslyn-sdk/blob/cc62642b58a306b2560a2367f1a0c11167ea3b2b/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs#L1216-L1231