chore: abort on Binding failures in uno56netcurrent
Context: 35ebc8b17056375a01bba8a64bbd99ff375d9a08

The problem: assume you have a `{Binding}` expression in XAML:

	<TextBlock AutomationProperties.AutomationId="HelloTextBlock"
	  Text="{Binding HelloText}"
	  HorizontalAlignment="Center" />

Further assume that `HelloText` doesn't exist on the in-scope
`DataContext` instance:

	partial class MainPage {
	  public MainPage()
	  {
	    InitializeComponent();
	    DataContext = this;
	  }
	  // No `HelloText` property
	}

The `{Binding HelloText}` will fail, but it fails *silently*.
The result is that the `<TextBlock/>` will be empty.

There are only two ways[^0] to detect that the `{Binding}` failed:

 1. Look at the UI and determine that the `<TextBlock/>` is empty,
    which is not ideal for automated testing.

 2. Log "all the things" and check the logs for an "appropriate"
    `fail` message:

        fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
              The [HelloText] property getter does not exist on type [unoapp.MainPage]

As it happens, (2) *can* be done on CI, *in-process*, by using the
[`ILoggingBuilder.AddFakeLogging()` extension method][0], in the
[Microsoft.Extensions.Diagnostics.Testing NuGet package][1]:

	partial class App {
	  public static void InitializeLogging()
	  {
	    // …
	    var factory = LoggerFactory.Create(builder => {
	      // …
	      builder.AddFakeLogging(options => {
	        options.FilteredCategories.Add("Uno.UI.DataBinding.BindingPropertyHelper");
	        options.OutputSink = message => {
	          if (message.Contains("property getter does not exist on type", StringComparison.Ordinal))
	          {
	            Environment.FailFast(message);
	          }
	          Console.WriteLine($"# jonp: Fake Message: {message}");
	        };
	      });
	    });
	    // …
	  }
	}

Here, we enable fake logging [^1], filter it against the
`Uno.UI.DataBinding.BindingPropertyHelper` category, and if the
message contains `property getter does not exist on type`, we abort
the process with extreme prejudice.

Now that we can detect a `{Binding}` failure, we need it to run on CI.
On CI, we run `uno56netcurrent --exit` (35ebc8b1), which hits our next
problem: the `{Binding}` error is only raised when the UI is rendered,
which is *after* `App.OnLaunched()` returns.

Fix that by giving the app a chance to render the UI before exiting
the process via `Task.Delay(1000)`:

	partial class App {
	  protected override async void OnLaunched(LaunchActivatedEventArgs args)
	  {
	    // …
	    if (args.Arguments?.Contains("--exit") ?? false) {
	      await Task.Run(async () => {
	        await Task.Delay(1000);
	        Exit();
	      });
	    }
	  }
	}

Which brings us to the final problem: we need a `{Binding …}` failure
*caused by Native AOT trimming the property*, which in turn is *fixed*
by #22676, i.e. there needs to be an indirection: it can't be a
property on a `[Bindable]` type -- the `[Bindable]` will preserve the
properties -- rather it needs to be on a *non-`[Bindable]` type* which
is referenced by a `[Bindable]` type.  But as types of `[Bindable]`
property types are preserved, we need *another* indirection.  Thus:

	<TextBlock AutomationProperties.AutomationId="HelloTextBlock"
	  Text="{Binding HelloModel.HelloEntity.Text}"
	  HorizontalAlignment="Center" />

alongside:

	partial class MainPage {
	  public MainPage()
	  {
	    InitializeComponent();
	    DataContext = new MainPageViewModel();;
	  }
	}

	[Microsoft.UI.Xaml.Data.Bindable]
	public record MainPageViewModel {
	  public HelloModel HelloModel { get; } = new HelloModel(new HelloEntity("Hello Uno Platform!"));
	}
	public record HelloModel(HelloEntity HelloEntity);
	public record HelloEntity(string Text);

Without #22676, `HelloEntity.Text` is trimmed away, causing the
`{Binding HelloModel.HelloEntity.Text}` to fail, which is what we want.
*With* #22676, `HelloEntity.Text` is preserved, and the
`{Binding HelloModel.HelloEntity.Text}` works.

With all of that in place, without the #22676 fix, we abort under
Native AOT:

	# Need to use Uno.Sdk.Private 6.6.x, as default 5.6.22 produces
	# error MSB4236: The SDK 'Uno.Sdk.Private' specified could not be found.
	% sed -i '' 's/"Uno.Sdk.Private": ".*"/"Uno.Sdk.Private": "6.6.0-dev.449"/g' src/SolutionTemplate/5.6/uno56netcurrent/global.json
	% dotnet publish -f net10.0-desktop -p:UnoTargetFrameworkOverride=net10.0-desktop \
	  -r osx-x64 -bl src/SolutionTemplate/5.6/uno56netcurrent/uno56netcurrent/*.csproj \
	  -p:IlcGenerateMapFile=true -p:IlcGenerateMstatFile=true -p:IlcGenerateDgmlFile=true -p:IlcGenerateMetadataLog=true \
	  -p:PublishAot=true -p:EmitCompilerGeneratedFiles=true -p:CompilerGeneratedFilesOutputPath=`pwd`/_gen
	% ./src/SolutionTemplate/5.6/uno56netcurrent/uno56netcurrent/bin/Release/net10.0-desktop/osx-x64/publish/uno56netcurrent --exit
	warn: Uno.UI.Runtime.Skia.MacOS.MacOSWindowNative[0]
	      Unable to find icon file [/Volumes/Xamarin-Work/src/unoplatform/uno/src/SolutionTemplate/5.6/uno56netcurrent/uno56netcurrent/bin/Release/net10.0-desktop/osx-x64/publish/Assets/Icons/iconStoreLogo.png] specified in the Package.appxmanifest file.
	fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
	      The [Text] property getter does not exist on type [uno56netcurrent.HelloEntity]
	Process terminated. [03:53.591, error] The [Text] property getter does not exist on type [uno56netcurrent.HelloEntity]
	   at System.RuntimeExceptionHelpers.FailFast(String, Exception, String, RhFailFastReason, IntPtr, IntPtr) + 0x129
	   at Microsoft.Extensions.Logging.Testing.FakeLogger.Log[TState](LogLevel, EventId, TState, Exception, Func`3) + 0x205
	   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|14_0[TState](LogLevel, EventId, ILogger, Exception, Func`3, List`1&, TState&) + 0x5f
	   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel, EventId, TState, Exception, Func`3) + 0x97
	   at Uno.UI.Adapter.Microsoft.Extensions.Logging.MicrosoftLogger.Log(LogLevel, String, Exception) + 0x98
	   at Uno.UI.DataBinding.BindingPropertyHelper.InternalGetPropertyType(Type, String, Boolean) + 0x343
	   at Uno.UI.DataBinding.BindingPropertyHelper.GetPropertyType(Type, String, Boolean) + 0x85
	   at Uno.UI.DataBinding.BindingPath.SubscribeToNotifyCollectionChanged(BindingPath.BindingItem) + 0x44
	   at Uno.UI.DataBinding.BindingPath.BindingItem.SubscribeToPropertyChanged() + 0x58
	   at Uno.UI.DataBinding.BindingPath.BindingItem.OnDataContextChanged() + 0xaa
	   at Uno.UI.DataBinding.BindingPath.BindingItem.set_DataContext(Object) + 0x37
	   at Uno.UI.DataBinding.BindingPath.BindingItem.set_DataContext(Object) + 0x37
	   at Uno.UI.DataBinding.BindingPath.OnDataContextChanged() + 0x4d
	   at Microsoft.UI.Xaml.Data.BindingExpression.ApplyBinding() + 0x14e
	   at Microsoft.UI.Xaml.Data.BindingExpression.set_DataContext(Object) + 0x89
	   at Microsoft.UI.Xaml.DependencyPropertyDetailsCollection.ApplyDataContext(Object) + 0x36
	   at Microsoft.UI.Xaml.DependencyObjectStore.OnDataContextChanged(Object, Object, DependencyPropertyValuePrecedences) + 0x73
	   at Microsoft.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty, Object, DependencyPropertyValuePrecedences, DependencyPropertyDetails, Boolean) + 0x20c
	   at Microsoft.UI.Xaml.DependencyObjectStore.OnParentPropertyChangedCallback(ManagedWeakReference, DependencyProperty, Object) + 0x1ba
	   at Microsoft.UI.Xaml.DependencyObjectStore.CallChildCallback(DependencyObjectStore, ManagedWeakReference, DependencyProperty, Object) + 0x4f
	   at Microsoft.UI.Xaml.DependencyObjectStore.InvokeCallbacks(DependencyObject, DependencyProperty, DependencyPropertyDetails, Object, DependencyPropertyValuePrecedences, Object, DependencyPropertyValuePrecedences, Boolean) + 0x130
	   at Microsoft.UI.Xaml.DependencyObjectStore.RaiseCallbacks(DependencyObject, DependencyPropertyDetails, Object, DependencyPropertyValuePrecedences, Object, DependencyPropertyValuePrecedences) + 0x3c7
	   at Microsoft.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty, Object, DependencyPropertyValuePrecedences, DependencyPropertyDetails, Boolean) + 0xa7b
	   at Microsoft.UI.Xaml.DependencyObjectStore.OnParentPropertyChangedCallback(ManagedWeakReference, DependencyProperty, Object) + 0x1ba
	   at Microsoft.UI.Xaml.DependencyObjectStore.CallChildCallback(DependencyObjectStore, ManagedWeakReference, DependencyProperty, Object) + 0x4f
	   at Microsoft.UI.Xaml.DependencyObjectStore.InvokeCallbacks(DependencyObject, DependencyProperty, DependencyPropertyDetails, Object, DependencyPropertyValuePrecedences, Object, DependencyPropertyValuePrecedences, Boolean) + 0x130
	   at Microsoft.UI.Xaml.DependencyObjectStore.RaiseCallbacks(DependencyObject, DependencyPropertyDetails, Object, DependencyPropertyValuePrecedences, Object, DependencyPropertyValuePrecedences) + 0x3c7
	   at Microsoft.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty, Object, DependencyPropertyValuePrecedences, DependencyPropertyDetails, Boolean) + 0xa7b
	   at Microsoft.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty, Object, DependencyPropertyValuePrecedences, DependencyPropertyDetails, Boolean) + 0x345
	   at Microsoft.UI.Xaml.Controls.ScrollViewer.OnApplyTemplate() + 0x16c
	   at Microsoft.UI.Xaml.FrameworkElement.InnerMeasureCore(Size) + 0x305
	   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) + 0x36a
	   at Microsoft.UI.Xaml.Controls.Control.MeasureOverride(Size) + 0x57
	   at Microsoft.UI.Xaml.FrameworkElement.InnerMeasureCore(Size) + 0x70b
	   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) + 0x36a
	   at Microsoft.UI.Xaml.Controls.ContentPresenter.MeasureOverride(Size) + 0x11e
	   at Microsoft.UI.Xaml.FrameworkElement.InnerMeasureCore(Size) + 0x70b
	   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) + 0x36a
	   at Microsoft.UI.Xaml.Controls.Control.MeasureOverride(Size) + 0x57
	   at Microsoft.UI.Xaml.FrameworkElement.InnerMeasureCore(Size) + 0x70b
	   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) + 0x36a
	   at Microsoft.UI.Xaml.Controls.ContentPresenter.MeasureOverride(Size) + 0x11e
	   at Microsoft.UI.Xaml.FrameworkElement.InnerMeasureCore(Size) + 0x70b
	   at Microsoft.UI.Xaml.Controls.Grid.MeasureOverride(Size) + 0x795
	   at Microsoft.UI.Xaml.FrameworkElement.InnerMeasureCore(Size) + 0x70b
	   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize) + 0x36a
	   at Microsoft.UI.Xaml.Controls.Control.MeasureOverride(Size) + 0x57
	   at Microsoft.UI.Xaml.FrameworkElement.InnerMeasureCore(Size) + 0x70b
	   at Uno.UI.Xaml.Islands.XamlIslandRoot.MeasureOverride(Size) + 0x365
	   at Microsoft.UI.Xaml.FrameworkElement.InnerMeasureCore(Size) + 0x70b
	   at Microsoft.UI.Xaml.UIElement.UpdateLayout() + 0x9ec
	   at Uno.UI.Xaml.Core.CoreServices.OnTick() + 0x1a8
	   at Uno.UI.Dispatching.NativeDispatcher.RunAction(NativeDispatcher, Action) + 0x7a
	   at Uno.UI.Dispatching.NativeDispatcher.DispatchItems() + 0x411
	   at Uno.UI.Runtime.Skia.MacOS.MacOSDispatcher.NativeToManaged(IntPtr) + 0x57
	   at Uno.UI.Runtime.Skia.MacOS.NativeMac.NSApplicationMain(Int32, IntPtr) + 0x3c
	   at Uno.UI.Runtime.Skia.MacOS.MacSkiaHost.RunLoop() + 0x19
	   at Uno.UI.Hosting.UnoPlatformHost.<RunCore>d__4.MoveNext() + 0x76
	   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&) + 0x44
	   at Uno.UI.Hosting.UnoPlatformHost.RunCore() + 0x2c
	   at Uno.UI.Hosting.UnoPlatformHost.Run() + 0x2c
	   at uno56netcurrent.Program.Main(String[] args) + 0x12a
	zsh: abort       --exit

With the #22676 fix, the app runs successfully.

[0]: https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.fakeloggerbuilderextensions.addfakelogging?view=net-10.0-pp#microsoft-extensions-logging-fakeloggerbuilderextensions-addfakelogging(microsoft-extensions-logging-iloggingbuilder-system-action((microsoft-extensions-logging-testing-fakelogcollectoroptions)))
[1]: https://www.nuget.org/packages/Microsoft.Extensions.Diagnostics.Testing
[2]: https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.debugsettings?view=windows-app-sdk-1.8

[^0]: To be fair, there may be other ways, but they don't work on Uno.
      The "obvious" alternative is to use the
      [`DebugSettings.BindingFailed` event][2], but that event is not
      raised in Uno, so it doesn't help here.
      Another WPF alternative *may* be to try using `ValidationRules`,
      but those *also* don't exist in Uno.

[^1]: Why is it "fake" logging?