chore: don't use Uno.UI.BindingHelper.Android for Java code
Context: 73b73b09cf3f783241f915d819c69e5801ea7103
Context: 8f7f7bc2b86aca49ac79737969426e6b457840de

`Uno.UI.Runtime.Skia.Android.csproj` explicitly adds
`UnoWebViewHandler.Android.cs` into `@(Compile)`, which means that
any changes to `UnoWebViewHandler.Android.cs` impacts the
`Uno.UI.Runtime.Skia.Android.csproj` build.

Thus, when 73b73b09 introduced new interface usage within
`UnoWebViewHandler.Android.cs`, this broke the build, as
`Uno.UI.Runtime.Skia.Android.csproj` didn't know about the new
`UnoWebViewHandlerJavascriptInterface` Java type.

Commit 8f7f7bc2 attempted to fix this by adding a `@(ProjectReference)`
to `Uno.UI.BindingHelper.Android` into `Uno.UI.Runtime.Skia.Android`.
This allowed things to build, but introduced a plethora of NuGet-
related errors (0cb3adb5) and now file errors:

	error XALNS7028: System.IO.FileNotFoundException:
	Could not load assembly 'Uno.UI.BindingHelper.Android, Version=255.255.255.255, Culture=neutral, PublicKeyToken='.
	Perhaps it doesn't exist in the Mono for Android profile?

Part of the conceptual problem here is that
`Uno.UI.Runtime.Skia.Android` uses types from
`src/Uno.UI` but not the entire infrastructure.  This is why adding
`Uno.UI.BindingHelper.Android` as an assembly reference failed: there's
too much "extra stuff" going on to prevent things from working.

Since the "cause" of the pain is that `Uno.UI.Runtime.Skia.Android`
is directly including files from `Uno.UI`, *continue* that path:
update `Uno.UI.Runtime.Skia.Android` to import
`UnoWebViewHandlerJavascriptInterface.java` as an
[`@(AndroidJavaSource)`][0].  This allows `Uno.UI.Runtime.Skia.Android`
to contain `IUnoWebViewHandlerJavascriptInterface` -- allowing it to
compile -- *without* using `Uno.UI.BindingHelper.Android`.

Alas, this requires updating `Uno.UI.Runtime.Skia.Android` to
add IDE0055 to `$(NoWarn)`, to ignore:

	src/Uno.UI.Runtime.Skia.Android/obj/**/generated/src/Uno.UI.IUnoWebViewHandlerJavascriptInterface.cs(6,17): error IDE0055: Fix formatting (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0055)
	src/Uno.UI.Runtime.Skia.Android/obj/**/generated/src/__NamespaceMapping__.cs(3,11): error IDE0055: Fix formatting (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0055)

This also requires enabling nullability on
`UnoWebViewHandler.Android.cs`, addressing:

	src/Uno.UI/UI/Xaml/Controls/WebView/Native/Android/UnoWebViewHandler.Android.cs(16,14):
	error CS8767: Nullability of reference types in type of parameter 'message' of 'void UnoWebViewHandler.PostMessage(string message)'
	  doesn't match implicitly implemented member 'void IUnoWebViewHandlerJavascriptInterface.PostMessage(string? p0)'
	  (possibly because of nullability attributes).

[0]: https://learn.microsoft.com/en-us/dotnet/android/building-apps/build-items#androidjavasource