chore: debug on CI!
(at least) two issues on CI.

Firstly, **Build - Managed Binaries > Build > Building WinAppSDK and Graphics3DGL package binaries**
fails due to file sharing:

	##[error]src\AddIns\Uno.WinUI.Graphics3DGL\Uno.WinUI.Graphics3DGL.csproj(66,3): Error MSB3923: Failed to download file "https://github.com/dotnet/Silk.NET/raw/a9c75a61528ee7b4e55442f5141cb132f10d72ff/src/Native/Silk.NET.OpenGLES.ANGLE.Native/runtimes/osx/native/libEGL.dylib".  The process cannot access the file 'C:\a\1\s\src\AddIns\Uno.WinUI.Graphics3DGL\angle_binaries\osx\libEGL.dylib' because it is being used by another process.

This is presumably due to updating `Uno.WinUI.Graphics3DGL.csproj` to
multi-target thing.  Update the `GetAngle` target so that we only
download `libEGL.dylib` for `$(NetUWPOrWinUI)`.

Secondly, **Tests - Unit Tests > Run > Run unit tests** fails:

	failed TestAndroidViewImplementingDependencyObject (819ms)
	  from C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators.Tests\bin\Release\net10.0\Uno.UI.SourceGenerators.Tests.dll (net10.0|x64)
	  Test method Uno.UI.SourceGenerators.Tests.DependencyObjectGeneratorTests.Given_DependencyObjectGenerator.TestAndroidViewImplementingDependencyObject threw exception:
	  System.InvalidOperationException: Mismatch between number of diagnostics returned, expected "1" actual "4"

	  Diagnostics:
	  // /0/Test0.cs(6,14): error Uno0003: 'Android.Views.View' shouldn't implement 'DependencyObject'. Inherit 'FrameworkElement' instead.
	  DiagnosticResult.CompilerError("Uno0003").WithSpan(6, 14, 6, 15).WithArguments("Android.Views.View"),
	  // /0/Test0.cs(3,20): error CS0234: The type or namespace name 'Dispatching' does not exist in the namespace 'Microsoft.UI' (are you missing an assembly reference?)
	  DiagnosticResult.CompilerError("CS0234").WithSpan(3, 20, 3, 31).WithArguments("Dispatching", "Microsoft.UI"),
	  // /0/Test0.cs(6,38): error CS0012: The type 'DispatcherQueue' is defined in an assembly that is not referenced. You must add a reference to assembly 'Uno.UI.Dispatching, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'.
	  DiagnosticResult.CompilerError("CS0012").WithSpan(6, 38, 6, 54).WithArguments("Microsoft.UI.Dispatching.DispatcherQueue", "Uno.UI.Dispatching, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null"),
	  // /0/Test0.cs(13,9): error CS0246: The type or namespace name 'DispatcherQueue' could not be found (are you missing a using directive or an assembly reference?)
	  DiagnosticResult.CompilerError("CS0246").WithSpan(13, 9, 13, 24).WithArguments("DispatcherQueue"),

This is *presumably* because some assembly references are missing
or not resolved.  What *is* being resolved?  Try to printf-debug this.