chore: Use Xamarin.AndroidX.Lifecycle.LiveData/2.8.7.4
Context: af83457dd7ac7e3aa0cc74e9d086626dffb58ca1

Similar to Xamarin.AndroidX.AppCompat in af83457d, the
Xamarin.AndroidX.Lifecycle.LiveData NuGet package had *two* releases
"two months ago": 2.8.7.4 and 2.9.0.

Usage of the newer 2.9.0 resulted in various NU1608 errors:

	C:\a\1\s\src\Uno.UI\Uno.UI.netcoremobile.csproj : error NU1608:
	Warning As Error: Detected package version outside of dependency constraint:
	Xamarin.AndroidX.Lifecycle.ViewModelSavedState 2.8.7.4 requires Xamarin.AndroidX.Lifecycle.LiveData.Core (>= 2.8.7.4 && < 2.8.8)
	but version Xamarin.AndroidX.Lifecycle.LiveData.Core 2.9.0 was resolved. [C:\a\1\s\Build\filters\Uno.UI-packages-netcoremobile.slnf]

Use Xamarin.AndroidX.Lifecycle.LiveData 2.8.7.4 to avoid the NU1608.

Local builds then hit another issue: the `AndroidX.DocumentFile`
namespace could not be resolved, resulting in a C# compilation error:

	src/Uno.UWP/Storage/StorageFolder.saf.Android.cs(31,21): error CS0246: The type or namespace name 'DocumentFile' could not be found (are you missing a using directive or an assembly reference?)

The cause for this is the Xamarin.AndroidX.Browser NuGet package:
[Xamarin.AndroidX.Browser/1.0.0][0] has a dependency on
Xamarin.AndroidX.Legacy.Support.Core.UI, which eventully pulls in
Xamarin.AndroidX.DocumentFile. [Xamarin.AndroidX.Browser/1.8.0.10][1]
*does not*.  The Xamarin.AndroidX.Legacy.Support.Core.UI dependency
was removed in Xamarin.AndroidX.Browser/1.2.0.

Fix the CS0246 by explicitly adding a reference to
Xamarin.AndroidX.DocumentFile.

Finally, fix some nullability and `[Obsolete]` errors caused by using
a newer Xamarin.AndroidX.DocumentFile package.

[0]: https://www.nuget.org/packages/Xamarin.AndroidX.Browser/1.0.0#dependencies-body-tab
[1]: https://www.nuget.org/packages/Xamarin.AndroidX.Browser/1.8.0.10#dependencies-body-tab