chore: Update to .NET 11 rc.1
Context: https://github.com/unoplatform/uno/issues/22745
Context: https://github.com/dotnet/android/pull/12750
Context: f42da0432d86bc5fc664cfc724221421744c9530

Update version numbers accordingly.

To sanity-check locally, try:

	\cp build/ci/net11/_global.json global.json

	dotnet build -f net11.0-ios26.5 src/Uno.Foundation/Uno.Foundation.netcoremobile.csproj
	dotnet build -f net11.0 src/Uno.UI/Uno.UI.csproj
	dotnet publish -f net11.0-android -p:UnoTargetFrameworkOverride=net11.0-android src/SamplesApp/SamplesApp/SamplesApp.csproj -p:UNO_DISABLE_ANALYZERS_IN_SAMPLES=true
	dotnet build -c Release -f net11.0-ios -p:UnoTargetFrameworkOverride=net11.0-ios src/SamplesApp/SamplesApp/SamplesApp.csproj

Fix trimmer warning:

  * IL2080:

        src/Uno.UI/UI/Xaml/Documents/UnicodeText.ICU.cs(249,19): error IL2080: 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.NonPublicMethods' in call to 'System.Type.GetMethod(String, BindingFlags)'. The field '(System.String, System.Type).Item2' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.

    which frankly feels like a bug in the trimmer; how did
    `ValueTuple<T1, T2>.Item2` get involved?

Note: Android+NativeAOT *still* fails to build by default, due to a
similar bug as in .NET 11 Preview 7; see also f42da043, e.g.

	Unable to find package Microsoft.NETCore.App.Runtime.NativeAOT.android-arm64 with version (= 11.0.0-rc.1.26428.117)
	  - Found 23 version(s) in nuget.org [ Nearest version: 11.0.0-rc.1.26425.128 ]
	  - Found 0 version(s) in /Users/jon/Downloads/dotnet-sdk-11.0.100-rc.1.26425.128/library-packs

Update the workaround within `Uno.CrossTargetting.targets`, and
cross fingers 🤞 that .NET 11 rc.2 doesn't require this workaround.