fix(trimer): Fix IL2026 JSON warnings in src/Uno.UI
Context: https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming
Context: https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation#specify-options

When building `src/Uno.UI` with trimmer warnings enabled (and turned up to 11):

	dotnet build  src/Uno.UI/Uno.UI.Skia.csproj -bl \
	  -p:TrimmerSingleWarn=false -p:_ExtraTrimmerArgs=--verbose -p:IsTrimmable=true -p:IsAotCompatible=true

Many of the warnings are around System.Text.Json usage:

	…/src/Uno.UI/UI/Xaml/FontManifestHelpers.cs(34,6): error IL2026:
	  Using member 'System.Text.Json.JsonSerializer.Deserialize<TValue>(Stream, JsonSerializerOptions)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code.
	  JSON serialization and deserialization might require types that cannot be statically analyzed.
	  Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved.

Update `JsonSerializer.Deserialize<TValue>()` usage to remove the
IL2026 warnings.

Specifically, update `CoreWebView2WebMessageReceivedEventArgs.cs` to
use `JsonSerializer.Deserialize<string>(string, JsonTypeInfo<string>)`,
providing a `JsonTypeInfo<string>` derived from a
`JsonSerializerOptions` instance that only supports strings.

Update `FontManifest*.cs` to use
[`JsonSourceGenerationOptionsAttribute`][0] so that System.Text.Json
source generation can generate an appropriate `JsonSerializerOptions`.
This allows us to use
`JsonSerializer.Deserialize<FontManifest>(Stream, JsonSerializerContext)`.

[0]: https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonsourcegenerationoptionsattribute?view=net-9.0