fix(trimer): Fix IL2026 JSON warnings in src/Uno.UI
Context: https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming
Context: https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation#specify-options

When building `src/Uno.UI` with trimmer warnings enabled (and turned up to 11):

	dotnet build  src/Uno.UI/Uno.UI.Skia.csproj -bl \
	  -p:TrimmerSingleWarn=false -p:_ExtraTrimmerArgs=--verbose -p:IsTrimmable=true -p:IsAotCompatible=true

Many of the warnings are around System.Text.Json usage:

	…/src/Uno.UI/UI/Xaml/FontManifestHelpers.cs(34,6): error IL2026:
	  Using member 'System.Text.Json.JsonSerializer.Deserialize<TValue>(Stream, JsonSerializerOptions)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code.
	  JSON serialization and deserialization might require types that cannot be statically analyzed.
	  Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved.

Update `JsonSerializer.Deserialize<TValue>()` usage to remove the
IL2026 warnings.

Update `FontManifest*.cs` to use
[`JsonSourceGenerationOptionsAttribute`][0] so that System.Text.Json
source generation can generate an appropriate `JsonSerializerOptions`.
This allows us to use
`JsonSerializer.Deserialize<FontManifest>(Stream, JsonSerializerContext)`.

*Note*: two runtime errors came up while making this change, and my
Google-Fu didn't provide good answers.  For posterity, the errors and
their fixes:

Firstly, an intermediate form of this PR would throw from
`JsonSerializer.Deserialize<FontManifest>(…)`:

	Unhandled exception. System.InvalidOperationException: TypeInfoResolver 'FontManifestSerializerContext' did not provide property metadata for type 'FontManifest'.

The fix for this is that
[`JsonSourceGenerationOptionsAttribute.GenerationMode`][1] needs to
specify *both* `.Metadata | .Serialization`:

	[JsonSourceGenerationOptions(
	  GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]

Secondly, an intermediate form of this PR would throw from
`JsonSerializer.Deserialize<FontManifest>(…)`:

	Unhandled exception. System.Text.Json.JsonException: The JSON value could not be converted to FontStyle. Path: $.fonts[0].font_style | LineNumber: …

The default enum deserialization behavior is to use the enum member
integral values, e.g. `2` for `FontStyle.Italic`, so it throws when
the string form is encountered:

	{ "font_style": "italic" }

The fix for this is to set
[`JsonSourceGenerationOptionsAttribute.UseStringEnumConverter`][2]=true.

[0]: https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonsourcegenerationoptionsattribute?view=net-9.0
[1]: https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonsourcegenerationoptionsattribute.generationmode?view=net-9.0
[2]: https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonsourcegenerationoptionsattribute.usestringenumconverter?view=net-9.0