chore: fix Tests - Android Native build
Context: dd5b4ffbea35657d2b68f04dea807fd3ce5b2de9

Looks like commit dd5b4ffb broke the **Tests - Android Native** stage:

	…/src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Input/Given_XYFocusTreeWalker.cs(23,14): error CS0260: Missing partial modifier on declaration of type 'Given_XYFocusTreeWalker'; another partial declaration of this type exists
	…/src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Input/Given_XYFocusTreeWalker.cs(198,23): error CS0260: Missing partial modifier on declaration of type 'FocusableXYFocusCUIElement'; another partial declaration of this type exists
	…/src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Input/Given_XYFocusTreeWalker.cs(208,23): error CS0260: Missing partial modifier on declaration of type 'XYFocusCUIElement'; another partial declaration of this type exists

Add the missing `partial` keyword so that this compiles.