chore: Bump to Preview 6
Context: https://github.com/dotnet/macios/releases/tag/dotnet-10.0.1xx-preview6-10451
Context: https://github.com/dotnet/sdk/issues/48949

The iOS, tvOS, and maccatalyst packages for .NET 10 Preview 6 no
longer contain 18.4 packages, they now ship 18.5 packages.
This necessitates a bunch of bumps everywhere.

Update the `%(KnownFrameworkReference.DefaultRuntimeFrameworkVersion)`,
`%(LatestRuntimeFrameworkVersion)`, and `%(TargetingPackVersion)`
values to match the .NET 10 Preview 6 version, to work around
dotnet/sdk#48949:

	error NU1102: Unable to find package Microsoft.WindowsDesktop.App.Ref with version (= 10.0.0-preview.6.25315.102)
	  - Found 146 version(s) in NuGet official package source [ Nearest version: 10.0.0-preview.6.25358.103 ]

Bump `$(LangVersion)`=13.0, in order to fix:

	src/Uno.Foundation/Uno.Core.Extensions/Uno.Core.Extensions.Collections/MemoryExtensions.cs(34,4):
	error CS9202: Feature 'ref struct interfaces' is not available in C# 12.0. Please use language version 13.0 or greater.