chore: Review use of $(TargetFramework)=net10.0, update to net11.0
**Tests - Desktop Skia {Linux,Windows} > Runtime Tests** reports
many failued unit tests such as within
`When_AlcAppXaml_HasSourceDictionary_Then_ResolvesToAlcSpecificDictionary`:

	Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Assert.Fail failed. AlcApp build failed with exit code 1.
	Output:   Determining projects to restore...
	  All projects are up-to-date for restore.
	  _UnoBaseReferenceBinPath: D:\a\1\s/build/samplesapp-desktop-skia
	D:\a\1\s\.dotnet\sdk\11.0.100-preview.5.26302.115\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(383,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [D:\a\1\s\src\Uno.UI.RuntimeTests\Tests\AssemblyLoadContext\AlcApp\Uno.UI.RuntimeTests.AlcApp.csproj]
	D:\a\1\s\.dotnet\sdk\11.0.100-preview.5.26302.115\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1005: Assets file 'D:\a\1\s\src\Uno.UI.RuntimeTests\Tests\AssemblyLoadContext\AlcApp\obj\project.assets.json' doesn't have a target for 'net11.0'. Ensure that restore has run and that you have included 'net11.0' in the TargetFrameworks for your project. [D:\a\1\s\src\Uno.UI.RuntimeTests\Tests\AssemblyLoadContext\AlcApp\Uno.UI.RuntimeTests.AlcApp.csproj]

	Build FAILED.

	D:\a\1\s\.dotnet\sdk\11.0.100-preview.5.26302.115\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1005: Assets file 'D:\a\1\s\src\Uno.UI.RuntimeTests\Tests\AssemblyLoadContext\AlcApp\obj\project.assets.json' doesn't have a target for 'net11.0'. Ensure that restore has run and that you have included 'net11.0' in the TargetFrameworks for your project. [D:\a\1\s\src\Uno.UI.RuntimeTests\Tests\AssemblyLoadContext\AlcApp\Uno.UI.RuntimeTests.AlcApp.csproj]
	    0 Warning(s)
	    1 Error(s)

	Time Elapsed 00:00:00.27

	Error:
	   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.Fail(String message) in /_/src/TestFramework/TestFramework/Assertions/Assert.Fail.cs:line 25
	   at Uno.UI.RuntimeTests.Tests.AssemblyLoadContext.Given_AlcContentHost.BuildAlcAppAsync() in D:\a\1\s\src\Uno.UI.RuntimeTests\Tests\AssemblyLoadContext\Given_AlcContentHost.cs:line 1687
	   at Uno.UI.RuntimeTests.Tests.AssemblyLoadContext.Given_AlcContentHost.StartSecondaryAlcAppAsync(String[] launchArguments) in D:\a\1\s\src\Uno.UI.RuntimeTests\Tests\AssemblyLoadContext\Given_AlcContentHost.cs:line 1533
	   at Uno.UI.RuntimeTests.Tests.AssemblyLoadContext.Given_AlcContentHost.When_AlcAppXaml_HasSourceDictionary_Then_ResolvesToAlcSpecificDictionary() in D:\a\1\s\src\Uno.UI.RuntimeTests\Tests\AssemblyLoadContext\Given_AlcContentHost.cs:line 282
	   at Uno.UI.Samples.Tests.UnitTestsControl.<>c__DisplayClass74_2.<<ExecuteTestsForInstance>g__InvokeTestMethod|5>d.MoveNext() in D:\a\1\s\src\SamplesApp\SamplesApp.UnitTests.Shared\Controls\UnitTest\UnitTestsControl.cs:line 1035

`Uno.UI.RuntimeTests.AlcApp.csproj` had `$(TargetFramework)`=net10.0.
This presumably needs to be updated to net11.0.

Meanwhile, an earlier commit in this PR mentioned:

> * When it makes sense to do so, use `$(NetPrevious)` and
>   `$(NetCurrent)` instead of hardcoding target frameworks.

The exception to this is `src/SolutionTemplate`.  Everywhere else,
when practical and known to import top-level `Directory.Build.props`,
should use `$(NetPrevious)` and `$(NetCurrent)` to simplify future
.NET bumps:

	% git grep -i '<targetframework.*net10' src | grep -v SolutionT