feat(win32): WebView2Aot backend for <WebView2/>
Fixes: https://github.com/unoplatform/uno/issues/23142

Context: https://github.com/MicrosoftEdge/WebView2Feedback/issues/5238
Context: https://github.com/smourier/WebView2Aot
Context: https://github.com/smourier/DirectNAot/issues/9

On Windows, the <WebView2/> XAML control is implemented in terms of
the [Microsoft.Web.WebView2 NuGet package][0].

The problem: Microsoft.Web.WebView2, when used for "normal" .NET,
uses COM Interop.  Native AOT does not support COM interop.
The result is that things fail, a'la
MicrosoftEdge/WebView2Feedback#5238 (which is for WinForms, but the
same fundamental idea).

In the case of #23142, if we build Uno.Gallery for Native AOT:

	git clone https://github.com/unoplatform/Uno.Gallery.git
	cd Uno.Gallery
	git checkout 54a08b1587aa020a5651d61eb3a3023a79e89d72
	sed -i '' 's/"Uno.Sdk": ".*"/"Uno.Sdk": "6.6.0-dev.216"/g' global.json
	dotnet publish -c Release -r win-arm64 -f net10.0-desktop -p:TargetFrameworkOverride=net10.0-desktop `
	  -bl Uno.Gallery/Uno.Gallery.csproj -p:SelfContained=true -p:UseSkiaRendering=true `
	  -p:SkiaPublishAot=true -p:IsAotCompatible=true

Run it:

	.\Uno.Gallery\bin\Release\net10.0-desktop\win-arm64\publish\Uno.Gallery.exe | Out-Default

and access the **UI components > WebView** entry in the left tree,
then the console contains the following output:

	fail: Uno.UI.Dispatching.NativeDispatcher[0]
	      NativeDispatcher unhandled exception
	      System.NotSupportedException: COM Interop requires ComWrapper instance registered for marshalling.
	         at System.Runtime.InteropServices.ComWrappers.ComInterfaceForObject(Object) + 0xa4
	         at System.Runtime.InteropServices.ComWrappers.ComInterfaceForObject(Object, Guid) + 0x24
	         at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String, String, ICoreWebView2EnvironmentOptions, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler) + 0xdc
	         at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__102.MoveNext() + 0xe4
	      --- End of stack trace from previous location ---
	         at Uno.UI.Runtime.Skia.Win32.Win32NativeWebView.<>c__DisplayClass15_0.<<-ctor>b__0>d.MoveNext() + 0x60
	      --- End of stack trace from previous location ---
	         at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__124_0(Object state) + 0x1c
	         at Uno.UI.Dispatching.NativeDispatcher.RunAction(NativeDispatcher, Action) + 0x8c

The Microsoft.Web.WebView2 package *does* support Native AOT, but
*only if* you're building for WinRT.  (Uno is not built on WinRT.)

A way to use Microsoft.Web.WebView2 while supporting Native AOT in a
"normal" (non-WinRT) Windows environment is to instead use
smourier/WebView2Aot, in the [WebView2Aot NuGet package][1].
WebView2Aot uses the [DirectN AOT generator][2] to emit Native AOT-
compatible COM interop infrastrucure.

Update `Uno.UI.Runtime.Skia.Win32` as follows:

 1. Split out the "native" bits of `Win32NativeWebView` into
    `Win32NativeWebViewBase.cs`.  (Anything dealing with a
    Windows WndProc, etc.)

 2. Update `Win32NativeWebView` to inherit `Win32NativeWebViewBase`.

 3. Add a new `Win32NativeAotWebView` type, which also inherits from
    `Win32NativeWebViewBase`.  This implements `<WebView2/>` support
    in terms of WebView2Aot.

However, WebView2Aot requires .NET 10.  Conseuqently,
`Uno.UI.Runtime.Skia.Win32.csproj` should only reference WebView2Aot
when targeting .NET 10 and later, and `Win32NativeAotWebView` can
only exist in .NET 10 and later.

Additionally, this is a potential significant change.  We want
WebView2Aot to be the default in all Windows configurations for
consistency -- nobody wants to debug a scenario of "WebView2 works
when I'm not building for Native AOT!" -- but there should be a way
to use the previous Microsoft.Web.WebView2 implementation in case
WebView2Aot breaks things, or for testing, or…

Update `Win32NativeWebViewProvider` as follows:

 1. When built for .NET 9, only Win32NativerWebView / the
    Microsoft.Web.WebView2 backend is supported.

 2. When built for .NET 10+, the new WebView2Aot backend is used by
    default.  This can be overridden by setting the
    `UNO_WEBVIEW2_BACKEND` environment variable to
    `microsoft.web.webview2`.

    `UNO_WEBVIEW2_BACKEND` can also be set to `webview2aot` to be
    explicit.

The `UNO_WEBVIEW2_BACKEND` environment variable is always read, and
will log an error message when using an unsupported value, e.g. when
`UNO_WEBVIEW2_BACKEND=webview2aot` on .NET 9.

Aside: add BannedApiAnalyzers to `Uno.UI.Runtime.Skia.Win32.csproj`
which make it an error to use `PWSTR.From(string)`.
See also smourier/DirectNAot#9.

[0]: https://www.nuget.org/packages/Microsoft.Web.WebView2
[1]: https://www.nuget.org/packages/WebView2Aot
[2]: https://github.com/smourier/DirectNAot