fix(trimmer): Fix IL3050 warnings around Enum use
When building `src/Uno.UI` with trimmer warnings enabled (and turned up to 11):

	dotnet build  src/Uno.UI/Uno.UI.Skia.csproj -bl \
	  -p:TrimmerSingleWarn=false -p:_ExtraTrimmerArgs=--verbose -p:IsTrimmable=true -p:IsAotCompatible=true

One of the warnings is:

	src/Uno.UI/UI/Xaml/Internal/InputManager.Pointers.ManagedDirectManip.cs(365,42): error IL3050:
	  Using member 'System.Enum.GetValues(Type)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling.
	  It might not be possible to create an array of the enum type at runtime.
	  Use the GetValues<TEnum> overload or the GetValuesAsUnderlyingType method instead.

Replace use of `System.Enum` methods which take a `Type` parameter
with their generic method overload:

  * `Enum.GetName(typeof(T), v)` becomes `Enum.GetName((T)v)`
  * `Enum.GetNames(typeof(T))` becomes `Enum.GetNames<T>()`
  * `Enum.GetValues(typeof(T))` becomes `Enum.GetValues<T>()`
  * `Enum.IsDefined(typeof(T), v)` becomes `Enum.IsDefined((T)v)`
  * `Enum.Parse(typeof(T), v)` becomes `Enum.Parse<T>(v)`

This fixes the IL3050 warnings.