ci: Downgrade BannedApiAnalyzer below the current C# compiler version
Avoids error messages like :
CSC error CS8032: An instance of analyzer Microsoft.CodeQuality.CSharp.Analyzers.ApiDesignGuidelines.CSharpImplementStandardExceptionConstructorsAnalyzer cannot be created from C:\hostedtoolcache\windows\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\analyzers\Microsoft.CodeAnalysis.CSharp.NetAnalyzers.dll : Method 'get_SupportedDiagnostics' in type 'Microsoft.CodeQuality.CSharp.Analyzers.ApiDesignGuidelines.CSharpImplementStandardExceptionConstructorsAnalyzer' from assembly 'Microsoft.CodeAnalysis.CSharp.NetAnalyzers, Version=6.0.5.1905, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.. [C:\a\1\s\src\Uno.UI.RemoteControl\Uno.UI.RemoteControl.Skia.csproj]