chore: Update to .NET 10 RC2
Context: 41a5796ea0a3a2d270999696ea7e0ce529755e41
Context: 92676ea716a37dfec6786b3fbfd4a8d230f1981f

On Android, .NET 10 RC2 fixed a number of issues which required
workarounds (41a5796e, 92676ea7), so remove the temporary workarounds.

On Apple platforms, the .NET 10 target framework versions changed
from `*18.5` to `*26.0`, e.g. from `net10.0-ios18.5` (.NET 10 RC1)
to `net10.0-ios26.0` (.NET 10 RC2).  Update everything as needed.

Apple platforms also now require Xcode-26.

On iOS, iOS 26 adds a new [`UIView.updateProperties()`][0] method,
which collides with the existing `Pivot.UpdateProperties()` method:

	src/Uno.UI/UI/Xaml/Controls/Pivot/Pivot.cs(120,16):
	  error CS0114: 'Pivot.UpdateProperties()' hides inherited member 'UIView.UpdateProperties()'.
	  To make the current member override that implementation, add the override keyword. Otherwise add the new keyword.
	src/SamplesApp/UITests.Shared/Windows_UI_Xaml/XamlRoot/XamlRoot_Properties.xaml.cs(39,15):
	  error CS0114: 'XamlRoot_Properties.UpdateProperties()' hides inherited member 'UIView.UpdateProperties()'.
	  To make the current member override that implementation, add the override keyword. Otherwise add the new keyword. [/Users/runner/work/1/s/src/SamplesApp/SamplesApp.netcoremobile/SamplesApp.netcoremobile.csproj::TargetFramework=net9.0-ios]

Rename the impacted `UpdateProperties()` methods to
`Update<EnclosingType>Properties`() to avoid [warning CS0114][1].

Additionally, `net9.0-ios18.5` no longer exists;
use `net9.0-ios18.0` instead.

Update `linuxVMImage`=[ubuntu-24.04][2] and
`linuxScaledPool`=Ubuntu2404-20251016, as the .NET 10 RC2
Android+Skia+NativeAOT build now requires NDK >= r27, and the
previous images only provided NDK r25.

Update `linux-install-deps.yml` to install `libwebkit2gtk-4.1-dev`,
as `libwebkit2gtk-4.0-dev` doesn't exist in `ubuntu-24.04`.

[0]: https://developer.apple.com/documentation/uikit/uiview/updateproperties()
[1]: https://learn.microsoft.com/dotnet/csharp/misc/cs0114
[2]: https://github.com/actions/runner-images/blob/d4d5736e7d5b88a683d1ea76e7dc74031c71d4c6/images/ubuntu/Ubuntu2404-Readme.md