chore(deps): Let's try AwesomeAssertions!
Context: https://github.com/unoplatform/uno/pull/21359

When runningthe SamplesApp.Skia.netcoremobile unit tests within a
NativeAOT environment, some of the tests fail with:

	System.NotSupportedException: 'FluentAssertions.Equivalency.GenericEnumerableEquivalencyStep.HandleImplSystem.Single' is missing native code. MethodInfo.MakeGenericMethod() is not compatible with AOT compilation. Inspect and fix AOT related warnings that were generated when the app was published. For more information see https://aka.ms/nativeaot-compatibility
	at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo1.GetUncachedMethodInvoker(RuntimeTypeInfo[], MemberInfo) + 0x2a
	    at System.Reflection.Runtime.MethodInfos.RuntimeMethodInfo.Invoke(Object, BindingFlags, Binder, Object[], CultureInfo) + 0x3f
	    at FluentAssertions.Equivalency.GenericEnumerableEquivalencyStep.Handle(IEquivalencyValidationContext, IEquivalencyValidator, IEquivalencyAssertionOptions) + 0x1d1
	    at FluentAssertions.Equivalency.EquivalencyValidator.RunStepsUntilEquivalencyIsProven(IEquivalencyValidationContext) + 0x9e
	    at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(EquivalencyValidationContext) + 0xd7
	    at FluentAssertions.Collections.CollectionAssertions2.BeEquivalentTo[TExpectation](IEnumerable1, Func2, String, Object[]) + 0x18b
	    at FluentAssertions.Collections.CollectionAssertions2.BeEquivalentTo[TExpectation](IEnumerable1, String, Object[]) + 0x88
	    at Uno.UI.RuntimeTests.Tests.Windows_UI_Xaml_Controls.Given_StackPanel.<When_Small_Elements_Horizontal_SnapPoints>d__9.MoveNext() + 0x15e
	--- End of stack trace from previous location ---
	    at Uno.UI.Samples.Tests.UnitTestsControl.<>c__DisplayClass67_2.<<ExecuteTestsForInstance>g__InvokeTestMethod|5>d.MoveNext() + 0x36d

It looks like FluentAssertions doesn't "like" NativeAOT.
(Or vice versa.  Whichever.)

Two related points here:

 1. Uno was using [FluentAssertions 5.10.3][0], which is *old*,
    released 2020-Mar-21.

 2. [FluentAssertions changed their license with v8.0][1].

There is thus incentive to move away from FluentAssertions, to solve
the licensing issue, and (*ideally*, maybe, eventually) to improve
support for NativeAOT.

[AwesomeAssertions][2] is a fork of FluentAssertions, which has the
same Apache-2.0 license as FluentAssertions 5.10.3 and is community
maintained.

Update the local world to use AwesomeAssertions.

*Note*: this does *not* provide NativeAOT support:

	System.NotSupportedException:
	      'AwesomeAssertions.Equivalency.Steps.GenericEnumerableEquivalencyStep.HandleImpl[System.ValueTuple`2[System.Int32,System.Object]](AwesomeAssertions.Equivalency.Steps.EnumerableEquivalencyValidator,System.Object[],System.Collections.Generic.IEnumerable`1[System.ValueTuple`2[System.Int32,System.Object]])'
	      is missing native code. MethodInfo.MakeGenericMethod() is not compatible with AOT compilation.
	      Inspect and fix AOT related warnings that were generated when the app was published.
	      For more information see https://aka.ms/nativeaot-compatibility
	    at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.GetUncachedMethodInvoker(RuntimeTypeInfo[], MemberInfo) + 0x2a
	    at System.Reflection.Runtime.MethodInfos.RuntimeMethodInfo.Invoke(Object, BindingFlags, Binder, Object[], CultureInfo) + 0x3f
	    at AwesomeAssertions.Equivalency.Steps.GenericEnumerableEquivalencyStep.Handle(Comparands, IEquivalencyValidationContext, IValidateChildNodeEquivalency) + 0x21a
	    at AwesomeAssertions.Equivalency.EquivalencyValidator.TryToProveNodesAreEquivalent(Comparands, IEquivalencyValidationContext) + 0x129
	    at AwesomeAssertions.Equivalency.EquivalencyValidator.AssertEquality(Comparands, EquivalencyValidationContext) + 0x43
	    at AwesomeAssertions.Collections.GenericCollectionAssertions`3.BeEquivalentTo[TExpectation](IEnumerable`1, Func`2, String, Object[]) + 0x203
	    at Uno.UI.RuntimeTests.Tests.Windows_UI_Xaml_Controls.Given_ListViewBase.<ContainerIndicesAreUpdated_OnRemoveAndAdd>d__49.MoveNext() + 0x177
	--- End of stack trace from previous location ---
	    at Uno.UI.Samples.Tests.UnitTestsControl.<>c__DisplayClass67_2.<<ExecuteTestsForInstance>g__InvokeTestMethod|5>d.MoveNext() + 0x36d

Thus, this provides a solution for the licensing conundrum, and
provides a *path* to future NativeAOT support, should someone update
AwesomeAssertions to support NativeAOT environments.

Notes: There have been *a lot* of API changes between FluentAssertions
and AwesomeAssertions, *other than* the namespace change, including:

  * `Be*OrEqualTo` is now `Be*ThanOrEqualTo`
  * `AssertionScope` has changed significantly.
  * `AssertionChain` has been introduced, largely but not entirely
    replacing `AssertionScope`.
  * `AssertionChain` is now a constructor parameter on
    `ReferenceTypeAssertion<…>` subclasses.
  * `.BeEquivalentTo(params object[])` is gone, but there *is* a
    `.BeEquivalentTo<T>(IEnumerable<T>)` overload, requiring
	replacing `.BeEquivalentTo(values)` with
	`.BeEquivalentTo([values])`.

See also:

  * https://awesomeassertions.org/upgradingtov6
  * https://awesomeassertions.org/upgradingtov8

[0]: https://www.nuget.org/packages/FluentAssertions/5.10.3
[1]: https://fluentassertions.com/releases/#800
[2]: https://awesomeassertions.org