chore: Fix trimmer warnings in src/Uno.UI
Context: https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming
Context: https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot#aot-compatibility-analyzers
Context: https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options
Context: 10480ec02ec24c8ba74aca0d25e94e461cfd4b0d
Context: 408e17789e8fd48f367a3012d6eb1bd6233d4538
Context: https://github.com/dotnet/android/issues/7473
Context: https://github.com/dotnet/android/commit/68368189d67c46ddbfed4e90e622f635c4aff11e

Enable `$(IsAotCompatible)`=true in `src/Uno.Foundation/*.csproj`.
Nothing is impacted in Uno.Foundation.

When building with trimmer warnings enabled and turned up to 11 in
`src/Uno.UI` for `src/Uno.UI/Uno.UI.Skia.csproj`:

	dotnet build src/Uno.UI/Uno.UI.Skia.csproj \
	  -p:TrimmerSingleWarn=false -p:_ExtraTrimmerArgs=--verbose \
	  -p:IsTrimmable=true -p:IsAotCompatible=true -bl

Address the following warnings:

	src/Uno.UI/DataBinding/BindingPropertyHelper.MemberBinder.cs(13,60): error IL3050:
	  Using member 'System.Dynamic.GetMemberBinder.GetMemberBinder(String, Boolean)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling.
	  Creating a call site may require dynamic code generation.
	src/Uno.UI/DataBinding/BindingPropertyHelper.MemberBinder.cs(22,60): error IL3050:
	  Using member 'System.Dynamic.SetMemberBinder.SetMemberBinder(String, Boolean)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling.
	  Creating a call site may require dynamic code generation.

Add `[RequiresDynamicCodeAttribute]` to the specified types.

Fix the following warnings:

	src/Uno.UI/UI/Xaml/Controls/WebView/Core/CoreWebView2WebMessageReceivedEventArgs.cs(61,70): error IL2026:
	  Using member 'System.Text.Json.Serialization.Metadata.JsonTypeInfo.CreateJsonTypeInfo<T>(JsonSerializerOptions)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code.
	  JSON serialization and deserialization might require types that cannot be statically analyzed and might need runtime code generation.
	  Use System.Text.Json source generation for native AOT applications.
	src/Uno.UI/UI/Xaml/Controls/WebView/Core/CoreWebView2WebMessageReceivedEventArgs.cs(61,70): error IL3050:
	  Using member 'System.Text.Json.Serialization.Metadata.JsonTypeInfo.CreateJsonTypeInfo<T>(JsonSerializerOptions)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling.
	  JSON serialization and deserialization might require types that cannot be statically analyzed and might need runtime code generation.
	  Use System.Text.Json source generation for native AOT applications.
	src/Uno.UI/UI/Xaml/Controls/WebView/Core/CoreWebView2WebMessageReceivedEventArgs.cs(54,22): error IL2026:
	  Using member 'System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.DefaultJsonTypeInfoResolver()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code.
	  JSON serialization and deserialization might require types that cannot be statically analyzed.
	  Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved.
	src/Uno.UI/UI/Xaml/Controls/WebView/Core/CoreWebView2WebMessageReceivedEventArgs.cs(54,22): error IL3050:
	  Using member 'System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.DefaultJsonTypeInfoResolver()' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling.
	  JSON serialization and deserialization might require types that cannot be statically analyzed and might need runtime code generation.
	  Use System.Text.Json source generation for native AOT applications.

@jonpryor was under the mistaken belief that commit 10480ec0 would be
sufficient to fix these warnings, and was wrong.  Even though we
"only" need to turn JSON into a *`string`*, not a structure, do as
requested: use System.Text.Json source generation.  (Which, again,
feels rather weird as only `string` is needed!)

	[JsonSourceGenerationOptions]
	[JsonSerializable(typeof(string))]
	internal sealed partial class ExampleContext : JsonSerializerContext {}
	// then use ExampleContext.Default.String to deserialize to string!

Fix the following warning:

	src/Uno.UI/UI/Xaml/SpecializedResourceDictionary.cs(133,34): error IL3050:
	  Using member 'System.Runtime.InteropServices.Marshal.SizeOf(Type)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling.
	  Marshalling code for the object might not be available.
	  Use the SizeOf<T> overload instead.

We *could* do as requested and use `Marshal.SizeOf<IntPtr>()`, but
the reason why `Marshal.SizeOf()` is used here is because of 408e1778,
which was to workaround dotnet/android#7473.  dotnet/android#7473 has
since been fixed in dotnet/android@68368189, meaning we don't actually
need to use `Marshal.SizeOf()` anymore.  Use `IntPtr.Size` instead.

Suppress the following warning:

	src/Uno.UI/UI/Xaml/Navigation/NavigationHistory.mux.cs(329,25): error IL2057:
	  Unrecognized value passed to the parameter 'typeName' of method 'System.Type.GetType(String)'.
	  It's not possible to guarantee the availability of the target type.

TODO: investigate whether we can update `PageStackEntry.m_descriptor`
to have `[DynamicallyAccessedMembers]`.

Suppress the following warnings:

	src/Uno.UI/Extensions/ViewExtensions.visual-tree.cs(214,4): error IL2075:
	  'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties' in call to 'System.Type.GetProperty(String, BindingFlags)'.
	  The return value of method 'System.Object.GetType()' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.
	src/Uno.UI/UI/Xaml/FrameworkElementExtensions.cs(82,17): error IL2075:
	  'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicFields', 'DynamicallyAccessedMemberTypes.NonPublicFields' in call to 'System.Reflection.TypeInfo.GetDeclaredField(String)'.
	  The return value of method 'System.Object.GetType()' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.
	src/Uno.UI/UI/Xaml/FrameworkElementExtensions.cs(82,17): error IL2075:
	  'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicFields', 'DynamicallyAccessedMemberTypes.NonPublicFields' in call to 'System.Reflection.TypeInfo.GetDeclaredField(String)'.
	  The return value of method 'System.Type.BaseType.get' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.
	src/Uno.UI/UI/Xaml/FrameworkElementExtensions.cs(108,20): error IL2075:
	  'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties', 'DynamicallyAccessedMemberTypes.NonPublicProperties' in call to 'System.Reflection.TypeInfo.GetDeclaredProperty(String)'.
	  The return value of method 'System.Object.GetType()' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.
	src/Uno.UI/UI/Xaml/FrameworkElementExtensions.cs(108,20): error IL2075:
	  'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties', 'DynamicallyAccessedMemberTypes.NonPublicProperties' in call to 'System.Reflection.TypeInfo.GetDeclaredProperty(String)'.
	  The return value of method 'System.Type.BaseType.get' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.
	src/Uno.UI/UI/Xaml/FrameworkElementExtensions.cs(104,8): error IL2070:
	  'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicFields', 'DynamicallyAccessedMemberTypes.NonPublicFields' in call to 'System.Reflection.TypeInfo.GetDeclaredField(String)'.
	  The parameter 'type' of method 'GetField(Type, String)' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.
	src/Uno.UI/UI/Xaml/FrameworkElementExtensions.cs(134,8): error IL2070:
	  'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties', 'DynamicallyAccessedMemberTypes.NonPublicProperties' in call to 'System.Reflection.TypeInfo.GetDeclaredProperty(String)'.
	  The parameter 'type' of method 'GetProperty(Type, String)' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.
	src/Uno.UI/DirectUI/PropertyPathStep.cs(502,16): error IL2072:
	  'pSourceType' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties' in call to 'DirectUI.ReflectionPropertyAccess.CreateInstance(IPropertyAccessHost, Object, Type, Boolean)'.
	  The return value of method 'System.Object.GetType()' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.
	src/Uno.UI/UI/Xaml/Controls/Frame/Frame.legacy.cs(68,4): error IL2072:
	  'value' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors' in call to 'Microsoft.UI.Xaml.Navigation.PageStackEntry.SourcePageType.set'.
	  The return value of method 'System.Object.GetType()' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.

As these callsites are all rooted in `value.GetType().…`, I can't
think of a way to appease NativeAOT here.

Address the following warnings:

	src/Uno.UI/DirectUI/PropertyAccess.cs(1634,18): error IL2070:
	  'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties' in call to 'System.Type.GetProperty(String, BindingFlags)'.
	  The parameter 'pSourceType' of method 'DirectUI.ReflectionPropertyAccess.CreateInstance(IPropertyAccessHost, Object, Type, Boolean)' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.
	src/Uno.UI/DirectUI/MetadataAPI.cs(603,5): error IL2070:
	  'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties', 'DynamicallyAccessedMemberTypes.NonPublicProperties' in call to 'System.Type.GetProperty(String, BindingFlags)'.
	  The parameter 'type' of method 'DirectUI.MetadataAPI.TryGetDependencyPropertyByName(Type, String)' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.
	src/Uno.UI/UI/Xaml/Navigation/PageStackEntry.Properties.cs(32,10): error IL2073:
	  'Microsoft.UI.Xaml.Navigation.PageStackEntry.SourcePageType.get' method return value does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors' requirements.
	  The return value of method 'Microsoft.UI.Xaml.Navigation.PageStackEntry.GetValue(DependencyProperty)' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.

Add the requested `[DynamicallyAccessedMembers]`.

Suppress the following warning:

	src/Uno.UI/UI/Xaml/Navigation/PageStackEntry.Properties.cs(41,3): error IL2111:
	  Method 'Microsoft.UI.Xaml.Navigation.PageStackEntry.PageStackEntry(Type, Object, NavigationTransitionInfo)' with parameters or return value with `DynamicallyAccessedMembersAttribute` is accessed via reflection.
	  Trimmer can't guarantee availability of the requirements of the method.

@jonpryor has no idea why this warning is appearing.

Address the following warning:

	src/Uno.UI/Helpers/TypeMappings.cs(76,6): error IL2072:
	  'type' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors' in call to 'System.Activator.CreateInstance(Type, params Object[])'.
	  The return value of method 'Uno.UI.Helpers.TypeMappings.GetReplacementType(Type)' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.

Update *the entire call hierarchy* within this file so that `Type`
parameters and `Type`-returning methods all declare *both*
`DynamicallyAccessedMemberTypes.PublicConstructors` and
`DynamicallyAccessedMemberTypes.PublicParameterlessConstructor`.
The latter is needed for `TypeMappings.CreateInstance<T>()`.

For the following warnings:

	src/Uno.UI/UI/Xaml/Markup/Reader/XamlTypeResolver.cs(463,23): error IL2075:
	  'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties' in call to 'System.Type.GetProperties()'.
	  The return value of method 'System.Type.BaseType.get' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.
	src/Uno.UI/UI/Xaml/Markup/Reader/XamlTypeResolver.cs(474,23): error IL2075:
	  'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods' in call to 'System.Type.GetMethods()'.
	  The return value of method 'System.Type.BaseType.get' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.

Annotate the `type` parameter with `[DynamicallyAccessedMembers]`.
(This doesn't touch `Type.BaseType`, but fixed the IL2075.)

TODO: Discuss with @jeromelaban why `XamlTypeResolver` goes through
`Func<…>` invocations instead of direct method calls, in particular
for `XamlTypeResolver.SourceIsAttachedProperty()`.  The use of
`Func<…>` causes an IL2111 after adding `[DynamicallyAccessedMembers]`.

TODO: for discussion, we have:

	src/Uno.UI/ToolkitHelper.cs(12,20): error IL2057: Unrecognized value passed to the parameter 'typeName' of method 'System.Type.GetType(String)'.
	  It's not possible to guarantee the availability of the target type.

`ToolkitHelper` is `internal`; Uno thus controls all callsites of
`ToolkitHelper.GetProperty()`.  We can thus fix this by updating
`ToolkitHelper.GetProperty()` to *remove* the `+ ",Uno.UI.Toolkit"`
string concatenation, and update all callsites, e.g. update
`CommandBarNavigationItemRenderer.UIKit.cs`:

	-ToolkitHelper.GetProperty("Uno.UI.Toolkit.CommandBarExtensions", "NavigationCommand")
	+ToolkitHelper.GetProperty("Uno.UI.Toolkit.CommandBarExtensions, Uno.UI.Toolkit", "NavigationCommand")

There are 13 such callsites.

Should we perform this change?