chore: .NET10 + Android + CS0246 fixes
Context: https://github.com/dotnet/android/commit/70bd636b

As part of .NET 10, .NET for Android introduced a new
`Microsoft.Android.Runtime` namespace.  This causes lots of CS0234
errors across the uno codebase:

	// Android.Views.Window Window => …
	error CS0234: The type or namespace name 'Views' does not exist in the namespace 'Microsoft.Android' (are you missing an assembly reference?)

While this requires .NET 10 to get the error, it doesn't require
.NET 10 to preemptively *fix* the error.  (And preemptively fixing
the error reduces the size of .NET 10 PRs…)

The CS0234 error can be fixed in (at least) three ways:

 1. Instead of a full type name such as `Android.Views.Window`,
    add a top-level `using Android.Views` and then only use
    `Window`.

    This approach only works if there is no other `Window` type in
    scope…which is *not* the case `Window`, but may be the case for
    other types such as `GravityFlags`.

 2. Use `global::`, e.g. `global::Android.Views.Window`.
    This *works*, but quickly gets verbose and unwieldy.

 3. [C# 10 `global using` directives][0] for `alias`es:

        global using AWindow = Android.Views.Window;

    then use `AWindow` when `Android.Views.Window` is needed.

Add a new `src/Uno.UI/GlobalUsings.cs` file which contains
`global using …` statements for the most commonly used types which
trigger CS0234 errors -- `AApplication`, `AButton`, `AWindow`, etc. --
and use a complication of (1) and (3) to fix the CS0234 errors.

Aside: Why a `A` prefix? For two reasons: (1) "A is for Android", and
(2) the aliases need to be "unique".  "Real" types take precedence over
`using` aliases; if we had `using Window = Android.Views.Window`,
*it would not matter* within a `Microsoft.UI.Xaml` namespace or sub-
namespace, as `Window` will *always* mean `Microsoft.UI.Xaml.Window`.

"While in the area", fix some new-in-.NET 10 IDE0055 warnings;
apparently a blank line is now required between a `namespace`
declaration and a type declaration.

Also fix some nullability warnings from the .NET 10 iOS bits.

[0]: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-directive#the-global-modifier