fix: Remove some duplicated namespaces
They end up causing errors when compiling locally, e.g. `dotnet build -f net6.0-ios` for SampleApp fails with:

```
/Users/poupou/git/external/uno/uno/src/Uno.UI.RuntimeTests/Helpers/RawBitmap.cs(11,7): error CS0105: The using directive for 'System.Runtime.InteropServices.WindowsRuntime' appeared previously in this namespace [/Users/poupou/git/external/uno/uno/src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.netcoremobile.csproj::TargetFramework=net6.0-ios]
/Users/poupou/git/external/uno/uno/src/Uno.UI.RuntimeTests/Helpers/RelativeCoords.cs(9,7): error CS0105: The using directive for 'System.Runtime.InteropServices.WindowsRuntime' appeared previously in this namespace [/Users/poupou/git/external/uno/uno/src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.netcoremobile.csproj::TargetFramework=net6.0-ios]
/Users/poupou/git/external/uno/uno/src/SamplesApp/SamplesApp.UITests/TestFramework/ImageAssert.Validations.cs(25,7): error CS0105: The using directive for 'Windows.UI.Xaml.Markup' appeared previously in this namespace [/Users/poupou/git/external/uno/uno/src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.netcoremobile.csproj::TargetFramework=net6.0-ios]

```