chore: Uno.WinUI.Graphics2DSK.nuspec targets .NET 9+10
Context: 69f1d49902dbdf0a04cb14a6211d3b0120ddcc9e
Context: 5c8d0e8b142c2c5e27d6c1a8eb3d61a504a801f6

I push 69f1d499, expecting to see progress on **Tests - Templates**.
Instead, **Build - Managed Binaries > Build > Generate NuGet Packages**
fails:

	EXEC : warning : NU5130: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder have compatible matches, but not exact matches in the other location. Unless intentional, consult the list of actions below: [C:\a\1\s\Build\Uno.UI.Build.csproj]
	  - Add a dependency group for .NETFramework9.0-windows10.0.19041.0 to the nuspec
	  NuGet Version: 5.4.0.6315
	  Attempting to build package from 'Uno.WinUI.Graphics2DSK.nuspec'.
	  Could not find a part of the path 'C:\a\1\s\src\AddIns\Uno.WinUI.Graphics2DSK\bin\Release\net8.0'.
	  System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\a\1\s\src\AddIns\Uno.WinUI.Graphics2DSK\bin\Release\net8.0'.
	     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
	     …
	C:\a\1\s\Build\Uno.UI.Build.csproj(355,3): error MSB3073: The command ".\external\nuget\NuGet.exe pack nuget\Uno.WinUI.Graphics2DSK.nuspec -Verbosity Detailed -Version "6.2.0-dev.154.g2b2e4d1b79" -Properties "NoWarn=NU5100,NU5105,NU5131;NU5123;branch=2b2e4d1b791cd1ed229b5bdf08ff32c113990042;commitid=2b2e4d1b791cd1ed229b5bdf08ff32c113990042;winuisourcepath=net9.0-windows10.0.19041.0;winuitargetpath=net9.0-windows10.0.19041.0"" exited with code 1.

It occurs to me that what probably happened is origin/master was
implicitly merged.  There were no merge conflicts, but this brought
in 5c8d0e8b, which reintroduces references to .NET 8 artifacts.

Merge in origin/master (bc5cc040), then update
`build/nuget/Uno.WinUI.Graphics2DSK.nuspec` so that .NET 8 artifacts
are no longer referenced.

This *should* fix the **Generate NuGet Packages** step.