chore: fix more build errors.
Update `FromNullableBoolToVisibilityConverter.cs` to fix
**Tests - Unit Tests > … > Build unit tests solution filter**:

	C:\a\1\s\src\Uno.UI.Tests\Converters\FromNullableBoolToVisibilityConverter.cs(30,79): error CS0103: The name 'IValueConverter' does not exist in the current context [C:\a\1\s\src\Uno.UI.Tests\Uno.UI.Unit.Tests.csproj::TargetFramework=net10.0]

From **Tests - WinAppSDK > Build Samples App > BUILDMSIX**,
we see warnings:

	D:\a\1\s\.dotnet\sdk\10.0.105\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(145,5): warning NETSDK1233: Targeting .NET 10.0 or higher in Visual Studio 2022 17.14 is not supported. [D:\a\1\s\src\SamplesApp\SamplesApp.Windows\SamplesApp.Windows.csproj]

Update the `.azure-devops-tests-winappsdk.yml` stage to use
`$(windowsScaledPool)`, which has an MSBuild which supports .NET 10.