test: ignore failing tests Android+NativeAOT tests.
Context: https://github.com/dotnet/android/issues/12542
Context: https://github.com/unoplatform/uno/issues/24270
Context: https://github.com/unoplatform/uno/issues/24271

Ignore the following test, which is a regression in dotnet/android;
see also dotnet/android#12542:

  * Given_WebView2.When_WebMessageReceived()

        Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Timed out waiting for condition to be met. When_WebMessageReceived():476
           at Private.Infrastructure.TestServices.WindowHelper.<WaitFor>d__41.MoveNext()
           --- End of stack trace from previous location ---
           at Uno.UI.RuntimeTests.Tests.Microsoft_UI_Xaml_Controls.Given_WebView2.<When_WebMessageReceived>d__10.MoveNext()
           --- End of stack trace from previous location ---
           at Uno.UI.Samples.Tests.UnitTestsControl.<>c__DisplayClass74_2.<<ExecuteTestsForInstance>g__InvokeTestMethod|5>d.MoveNext()

  * Given_WebView2.When_WebMessageReceived_After_RemoveAdd():
    Hangs on CI, as the test didn't have a `[Timeout]`.

Ignore the following test, which is probably some floating-point
related issue that needs more investigation; see also #24270:

  * Given_AnimatedVisualPlayer.When_Reverse_Negative_PlaybackRate_Animation_Completes_At_One():

        Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Assert.AreEqual failed. Expected a difference no greater than <0.02> between expected value <0.2223382443189621> and actual value <0.25255224108695984>. 'expected' expression: 'frozenProgress', 'actual' expression: 'GetPlayerProgress(player)'. A zero playback rate should freeze the current progress.
           at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.ThrowAssertAreEqualFailed[T](T expected, T actual, T delta, String userMessage) in //src/TestFramework/TestFramework/Assertions/Assert.AreEqual.cs:line 679
           at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.AreEqual(Double expected, Double actual, Double delta, String message, String expectedExpression, String actualExpression) in //src/TestFramework/TestFramework/Assertions/Assert.AreEqual.cs:line 1149
           at Uno.UI.RuntimeTests.Tests.Microsoft_UI_Xaml_Controls.Given_AnimatedVisualPlayer.When_PlaybackRate_Zero_Keeps_Progress_Stable()
           at Uno.UI.Samples.Tests.UnitTestsControl.<>c__DisplayClass74_2.<<ExecuteTestsForInstance>g__InvokeTestMethod|5>d.MoveNext()

Ignore the following tests, which are failing for reasons @jonpryor
doesn't understand; see also #24271:

  * Given_BitmapSource.When_MsAppData()

        System.TimeoutException: The operation has timed out.
           at Uno.UI.RuntimeTests.Tests.Windows_UI_Xaml_Media_Imaging.Given_BitmapSource.<When_MsAppData>d__3.MoveNext()
           --- End of stack trace from previous location ---
           at Uno.UI.Samples.Tests.UnitTestsControl.<>c__DisplayClass74_2.<<ExecuteTestsForInstance>g__InvokeTestMethod|5>d.MoveNext()

  * Given_WebView2.When_LocalFolder_File()

        Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Timed out waiting for condition to be met. When_LocalFolder_File():343
           at Private.Infrastructure.TestServices.WindowHelper.<WaitFor>d__41.MoveNext()
           --- End of stack trace from previous location ---
           at Uno.UI.RuntimeTests.Tests.Microsoft_UI_Xaml_Controls.Given_WebView2.<<When_LocalFolder_File>g__Do|7_0>d.MoveNext()
           --- End of stack trace from previous location ---
           at Uno.UI.RuntimeTests.Helpers.TestHelper.<RetryAssert>d__1.MoveNext()
           --- End of stack trace from previous location ---
           at Uno.UI.RuntimeTests.Helpers.TestHelper.<RetryAssert>d__1.MoveNext()
           --- End of stack trace from previous location ---
           at Uno.UI.RuntimeTests.Tests.Microsoft_UI_Xaml_Controls.Given_WebView2.<When_LocalFolder_File>d__7.MoveNext()
           --- End of stack trace from previous location ---
           at Uno.UI.Samples.Tests.UnitTestsControl.<>c__DisplayClass74_2.<<ExecuteTestsForInstance>g__InvokeTestMethod|5>d.MoveNext()