chore: fix Tests - Android Native > Run Android Tests
Context: 03c71f6a7bc94f9b47518c1a5b58e4b92f47f7eb

Commit 03c71f6a addressed some linker warnings by introducing a new
`SampleChooserType` struct to ensure that reflection metadata was
preserved.

Unfortunately this change to `src/SamplesApp/SamplesApp.UITests.Generator`
also impacted `src/SamplesApp/SamplesApp.UITests`; from a build log:

    /agent/_work/1/s/src/SamplesApp/SamplesApp.UITests/obj/Release/net9.0/Uno.Samples.UITest.Generator/Uno.Samples.UITest.Generator.SamplesListGenerator/AllSamplesList.g.cs(6,12):
    error CS0246: The type or namespace name 'SampleChooserType' could not be found (are you missing a using directive or an assembly reference?) [/agent/_work/1/s/src/SamplesApp/SamplesApp.UITests/SamplesApp.UITests.csproj]

Fix this by moving the definition of `SampleChooserType` into
`SamplesListGenerator.cs` / the generated `AllSamplesList.g.cs`.
This allows the `src/SamplesApp/SamplesApp.UITests` to have access
to the type, allowing `AllSamplesList.g.cs` to compile stand-alone.