chore: Update to .NET 10 RC1
Context: 69cc392740d79597b3f8e1a846d0562732c134ac
Context: https://github.com/aspnet/Announcements/issues/526

ASP.NET Core deprecated `WebHostBuilder` in .NET 10 RC1.
Instead of following their migration logic, `#pragma warning disable`
the relevant warnings.  This is because we still support .NET 9, and
we don't yet know if their new code will work on .NET 9.

We can update this next year, when `$(NetPrevious)`=net10.0.

The bump to .NET 10 RC1 also "introduced" lots of IL2122 errors:

	src/Uno.UI/UI/Xaml/Controls/ColorPicker/ColorPickerSliderAutomationPeer.cs(80,8): error IL2122:
	Type 'Microsoft.UI.Xaml.Automation.ValuePatternIdentifiers' is not assembly qualified. Type name strings used for dynamically accessing a type should be assembly qualified.

@jonpryor *suspects* that this may be due to the introduction of
`[DynamicallyAccessedMembers]` in various places within 69cc3927.

Update the various `ApiInformation.Is*Present()` invocations to
assembly-qualify the type names based on Uno assembly names, e.g.
`Microsoft.UI.Xaml.Automation.ValuePatternIdentifiers, Uno.UI`.

This does *not* apply to `ApiInformation.IsApiContractPresent()`,
which does NOT take an assembly-qualified type name; it's a constant.