chore: Fix Uno.UI.Runtime.Skia.Android.csproj build
Context: ca9231045fb10d2ecca2be75a4fa8461fdaa879c

The addition and use of `GlobalUsings.cs` in ca923104 broke the
`Uno.UI.Runtime.Skia.Android.csproj` build as it wasn't importing it:

	src/Uno.UI/UI/Xaml/NativeApplication.cs(25,35): error CS0246: The type or namespace name 'AApplication' could not be found (are you missing a using directive or an assembly reference?)

Update `Uno.UI.Runtime.Skia.Android.csproj` so that
`GlobalUsings.cs` is part of `@(Compile)`, allowing it to build.