chore: Undo addition of IValueConverter.TargetTypeRequirements
Context: 14d0b8624b3c769c28110c420f0b519674a89963

Commit 14d0b862 stated:

> In a "is this a good or bad idea" mement, add trimmer annotations to
> `IValueConverter`.  This in turn requires *half the universe* to be
> updated to have matching annotations.

I can say that, in retrospect, this was a bad idea.  It created a
divergence from upstream WPF, requiring different-ish codepaths between
Uno and WinAppSDK and everything tangentially related, such as
**Tests - Unit Tests > Run > Run unit tests**, which fails with:

	// /0/Test0.cs(35,83): error CS0117: 'IValueConverter' does not contain a definition for 'TargetTypeRequirements'
	DiagnosticResult.CompilerError("CS0117").WithSpan(35, 83, 35, 105).WithArguments("Microsoft.UI.Xaml.Data.IValueConverter", "TargetTypeRequirements"),
	// /0/Test0.cs(40,87): error CS0117: 'IValueConverter' does not contain a definition for 'TargetTypeRequirements'
	DiagnosticResult.CompilerError("CS0117").WithSpan(40, 87, 40, 109).WithArguments("Microsoft.UI.Xaml.Data.IValueConverter", "TargetTypeRequirements"),

At this point, the experiment is over: it's not currently viable to try
to update `IValueConverter` to be more Native AOT friendly.

Revert the lot of it; we'll have to address the resulting trimmer
warnings by suppressing them.