chore: fix CS1705 errors
Context: eecf28ba0c477f4b40673eda0b27da5640f6e070
Context: https://github.com/dotnet/sdk/issues/48949

Building `build/filters/Uno.UI-packages-skia.slnf` would error out:

	CSC : error CS1705: Assembly 'Microsoft.Win32.SystemEvents' with identity 'Microsoft.Win32.SystemEvents, Version=10.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
	uses 'System.Runtime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime'
	with identity 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'8

This happened when building `Uno.UI.Runtime.Skia.Wpf.csproj` with
`$(TargetFramework)=net9.0`.

Where were the .NET 10 packages coming from?

The .NET 10 packages were coming from eecf28ba, which overrode e.g.
`%(KnownFrameworkReference.TargetingPackVersion)` to the "correct"
.NET 10 package version, but the way this was done *also* caused
.NET *9* builds to use the .NET 10 packages!

Oops.

Update the `Condition` on `@(KnownFrameworkReference)` so that the
fixups to workaround dotnet/sdk#48949 are only applied for
`$(TargetFramework)`s of .NET 10.