chore: Update to .NET 11 Preview 4
Context: https://github.com/unoplatform/uno/issues/22745
Context: https://github.com/unoplatform/uno.templates/issues/1992
Context? 69cc392740d79597b3f8e1a846d0562732c134ac

It's that time of year again!  .NET 11 previews are out;
does Uno work with .NET 11?  Let's find out!

Build system changes and notes:

  * Leave `FontFallbackPreprocessor.csproj` targeting net10.0,
    as this job never provisions .NET itself, and .NET 10 is
    pre-installed on that CI bot.

  * Update `$(macOSVMImage)` to use `macOS-26` (up from `macOS-15`).
    dotnet/macios in .NET 11 now requires Xcode 26.4, and only
    the [macOS-26 runner-image][0] provides Xcode 26.4.x.

  * Update `$(windowsScaledPool)`to use `Windows2025-20260406-1`.
    The **Building WinAppSDK and Graphics3DGL package binaries** and
    **BuildMSIX** steps failed on CI because .NET 11 requires
    MSBuild 18, which in turn requires Visual Studio 2026.  The prior
    `Windows2022*` bots only have Visual Studio *2022*, resulting in:

        Version 11.0.100-preview.2.26159.112 of the .NET SDK requires at least version 18.0.0 of MSBuild. The current available version of MSBuild is 17.14.14.31908. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

    This also requires updating `.azure-devops-tests-winappsdk.yml` to
    use *pool name* `$(windowsScaledPool)` instead of *image name*
    `$(windows2022HostedVMImage)`,

    *Note*: *pool names* have a `$(…Pool)` suffix, and need to be used
    as `pool: $(…Pool)`, while *image names* have a `$(…VMImage)`
    suffix and are used as `pool: vmImage: $(…VMImage)`.

  * When it makes sense to do so, use `$(NetPrevious)` and
    `$(NetCurrent)` instead of hardcoding target frameworks.

  * Introduce new `$(NetPreviousAppleOSVersion)` and
    `$(NetCurrentAppleOSVersion)` MSBuild properties to avoid
    hardcoding Apple OS versions.

  * net11.0-ios and net11-tvos bump the minimum supported
    `$(SupportedOSPlatformVersion)` value to 13.0.

  * `skia-ios-uitest-build.sh` needs to target `net10.0-ios26.4`
    so that it uses the same Xcode version as net11.0-ios26.4.
    Fixes:

        error : This version of .NET for iOS (26.0.11017) requires Xcode 26.0.

  * Duplicate various `<ItemGroup/>`s to add support for net11.0*.
    (Duplicate instead of update existing item groups so that if in
    the future we need to e.g. change package versions, we can do so
    with minimal noise.)

  * Bump NuGet Package versions for .NET 11 Android; resolves:

        Missing class javax.lang.model.element.Modifier (referenced from: javax.lang.model.element.Modifier[] com.google.errorprone.annotations.IncompatibleModifiers.value() and 1 other context)

  * Bump `Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing`
    NuGet package version to 1.1.3, so that we can use e.g.
    `ReferenceAssemblies.Net.Net100`.

  * However, updating those package versions means we need to bump
    `$(SupportedOSPlatformVersion)` to 23 (up from 21).
    Update that in `Uno.CrossTargetting.targets`, and *remove*
    `$(SupportedOSPlatformVersion)` from
    `SamplesApp*.netcoremobile.csproj` as those are "confusing noise";
    they're not used, as `Uno.CrossTargetting.targets` always replaces.

  * Some of the updated .NET 11 Android NuGet packages also broke API
    in various ways; update `UnoExploreByTouchHelper.cs` to compensate.

  * Fix NU1510 errors by removing `@(PackageReference)`s for the
    mentioned packages: Microsoft.Extensions.Logging.Abstractions,
    Microsoft.CSharp, System.Formats.Asn1, System.Net.Http,
    System.Text.RegularExpressions.

  * Reminder: `.azure-devops-tests-ios-skia-build.yml` must be
    consistent with `skia-ios-uitest-build.sh`, and

Source code changes:

  * Apple platforms such as net11.0-ios26.4 have changed nullability
    of methods such as `NSObject.FromObject()`.  Compensate.

	  While updating nullability, also update nearby logic errors.
    `UnoWKWebView.ProcessNavigation()` calls `relativePath.Substring(1)`
    if `relativePath` starts with a `/`, but if it were to start with
    *multiple* slashes, the result would still start with a slash.
    Use `resultPath.TrimStart('/')` instead.

    `SvgImageSource.OpenSvgBundle()` could have `fileExtension==""`
    and would then call `fileExtension.Substring(1)`, which could
    throw.  Use `fileExtension.TrimStart('.')` instead.

  * `object.ToString()` has long returned nullable `string?`, but
    only now is it apparently impacting
    `NativeCoreWebView2HttpRequestHeaders.iOS.cs`.  (Go figure.)

  * .NET 11 has new IDE0055 warnings for pre-existing constructs;
    in particular, `else if` must be on the same line, and
    `#region`/`#endregion` must have matching indentation.

    Update various files to fix these warnings.

  * Trimmer fixes! TODO description.

  * Update `Given_BrowserKeyboardInputSource.cs` to use
    `Type.GetType(string)` instead of
    `AppDomain.CurrentDomain.GetAssemblies().FirstOrDefault(…).GetType(…)`
    to fix IL2026 and IL2072 warnings:

        Given_BrowserKeyboardInputSource.cs(43,5): error IL2026: Using member 'System.Reflection.Assembly.GetType(String)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Types might be removed by trimming. If the type name is a string literal, consider using Type.GetType instead.
        Given_BrowserKeyboardInputSource.cs(50,18): error IL2072: 'type' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors', 'DynamicallyAccessedMemberTypes.NonPublicConstructors' in call to 'System.Runtime.CompilerServices.RuntimeHelpers.GetUninitializedObject(Type)'. The return value of method 'System.Reflection.Assembly.GetType(String)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
        Given_BrowserKeyboardInputSource.cs(53,22): error IL2075: 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicEvents' in call to 'System.Type.GetEvent(String, BindingFlags)'. The return value of method 'System.Reflection.Assembly.GetType(String)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
        Given_BrowserKeyboardInputSource.cs(58,18): error IL2075: 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.NonPublicMethods' in call to 'System.Type.GetMethod(String, BindingFlags)'. The return value of method 'System.Reflection.Assembly.GetType(String)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.

  * Update `SamplesApp.netcoreapp.csproj` to ignore IL2026 warnings
    from `System.Data`:

        error IL2026: System.Data.DataSet.System.Xml.Serialization.IXmlSerializable.GetSchema(): Using member 'System.Data.DataSet.WriteXmlSchema(DataSet, XmlWriter)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. DataSet.GetSchema uses TypeDescriptor and XmlSerialization underneath which are not trimming safe. Members from serialized types may be trimmed if not referenced directly.
        error IL2026: System.Data.DataSet.System.Xml.Serialization.IXmlSerializable.ReadXml(XmlReader): Using member 'System.Data.DataSet.ReadXmlSerializableInternal(XmlReader)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. DataSet.ReadXml uses XmlSerialization underneath which is not trimming safe. Members from serialized types may be trimmed if not referenced directly.
        error IL2026: System.Data.DataSet.System.Xml.Serialization.IXmlSerializable.WriteXml(XmlWriter): Using member 'System.Data.DataSet.WriteXmlInternal(XmlWriter)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. DataSet.WriteXml uses XmlSerialization underneath which is not trimming safe. Members from serialized types may be trimmed if not referenced directly.
        error IL2026: System.Data.DataTable.System.Xml.Serialization.IXmlSerializable.GetSchema(): Using member 'System.Data.DataTable.GetXmlSchema()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. DataTable.GetSchema uses TypeDescriptor and XmlSerialization underneath which are not trimming safe. Members from serialized types may be trimmed if not referenced directly.
        error IL2026: System.Data.DataTable.System.Xml.Serialization.IXmlSerializable.ReadXml(XmlReader): Using member 'System.Data.DataTable.ReadXmlSerializableInternal(XmlReader)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. DataTable.ReadXml uses XmlSerialization underneath which is not trimming safe. Members from serialized types may be trimmed if not referenced directly.
        error IL2026: System.Data.DataTable.System.Xml.Serialization.IXmlSerializable.WriteXml(XmlWriter): Using member 'System.Data.DataTable.WriteXmlInternal(XmlWriter)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. DataTable.WriteXml uses XmlSerialization underneath which is not trimming safe. Members from serialized types may be trimmed if not referenced directly.
        error IL2026: System.ComponentModel.DefaultValueAttribute.DefaultValueAttribute(Type, String): Using member 'System.ComponentModel.DefaultValueAttribute.<.ctor>g__TryConvertFromInvariantString|4_0(Type, String, Object&)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. DefaultValueAttribute usage of TypeConverter is not compatible with trimming.

Commands to migrate from net9+net10 to net10+net11, for posterity:

	git grep -l 'net10\.0' | while read file ; do sed -i '' 's/net10\.0/net11\.0/g' $file ; done
	git grep -l 'net9\.0'  | while read file ; do sed -i '' 's/net9\.0/net10\.0/g' $file ; done

	git grep -l net10.0-ios18.0         | while read file ; do sed -i '' 's/net10.0-ios18.0/net10.0-ios26.0/g' $file ; done
	git grep -l net10.0-tvos18.0        | while read file ; do sed -i '' 's/net10.0-tvos18.0/net10.0-tvos26.0/g' $file ; done
	git grep -l net10.0-maccatalyst18.0 | while read file ; do sed -i '' 's/net10.0-maccatalyst18.0/net10.0-maccatalyst26.0/g' $file ; done

	git grep -l net11.0-ios26.0         | while read file ; do sed -i '' 's/net11.0-ios26.0/net11.0-ios26.4/g' $file ; done
	git grep -l net11.0-tvos26.0        | while read file ; do sed -i '' 's/net11.0-tvos26.0/net11.0-tvos26.4/g' $file ; done
	git grep -l net11.0-maccatalyst26.0 | while read file ; do sed -i '' 's/net11.0-maccatalyst26.0/net11.0-maccatalyst26.4/g' $file ; done

`@(PackageReference)` needs to be reviewed, as the above "in-place"
updates mean that "net10.0" is using the same packages as "net9.0",
which are almost certainly wrong.  To easily find files to review:

	git status | grep modified: | cut -c 14- | while read file ; do
	  if git diff HEAD^ $file | grep '<PackageReference' >/dev/null 2>&1 ; then
	    echo $file
	  fi
	done > review.txt

To sanity-check locally, try:

	cp build/ci/net11/_global.json global.json
	export PATH=/location/of/net11:$PATH
	dotnet build -f net11.0 src/Uno.Foundation/Uno.Foundation.csproj
	dotnet build -f net11.0 src/Uno.UI/Uno.UI.Skia.csproj
	dotnet build -f net11.0-android src/Uno.UI/Uno.UI.netcoremobile.csproj
	dotnet build -f net11.0-android src/SamplesApp/SamplesApp.Skia.netcoremobile/SamplesApp.Skia.netcoremobile.csproj
	dotnet publish -f net11.0-android src/SamplesApp/SamplesApp.Skia.netcoremobile/SamplesApp.Skia.netcoremobile.csproj -p:RunAOTCompilation=false -p:UnoTargetFrameworkOverride=net11.0-android -p:UNO_DISABLE_ANALYZERS_IN_SAMPLES=true -bl
	dotnet build -f net10.0-ios -c Release -p:UnoTargetFrameworkOverride=net10.0-ios -bl src/SamplesApp/SamplesApp.netcoremobile/SamplesApp.netcoremobile.csproj

TODO:

  * When unoplatform/uno.templates supports .NET 11
    (unoplatform/uno.templates#1992), update
    `RealAppLaunchIntegrationTests.cs._targetFramework` to net11.0.

[0]: https://github.com/actions/runner-images/blob/9e3319d6b4acc306925295853d0ff41ddd5c40f0/images/macos/macos-26-Readme.md#xcode