chore: fix WinAppSDK-related build errors
**Tests - Win AppSDK > Build Samples App > BuildMSIX** fails because
it uses the WPF `IValueConverter` type instead of Uno's:

    D:\a\1\s\src\Uno.UI.RuntimeTests\Tests\Windows_UI_Xaml\Controls\When_Refresh_Setter_BindingOnInvocation.xaml.cs(31,83): error CS0117: 'IValueConverter' does not contain a definition for 'TargetTypeRequirements'

Add a new `Uno.UI.RuntimeTests.Helpers.Annotations` type which can
be used for the annotation value instead.