chore: Remove `Android.` from IFrameworkElementImplementation.Android.tt
See also: ca9231045fb10d2ecca2be75a4fa8461fdaa879c, fd14b3ebd9dd62f8c44194780ec0f1dcc93545ef

The generated file `src\Uno.UI\Mixins\Android\FrameworkElementMixins.g.cs`
failed to build:

	src\Uno.UI\Mixins\Android\FrameworkElementMixins.g.cs(4168,63):
	Error CS0234: The type or namespace name 'Views' does not exist in the namespace 'Microsoft.Android' (are you missing an assembly reference?)

Update `IFrameworkElementImplementation.Android.tt` to remove
`Android.Views`.  There was already a `using Android.Views` at
toplevel, so it wasn't needed anyway.