chore: avoid Task.Wait() on SkiaWasm
**Tests - WebAssembly Skia > Run Runtime Tests *:** are failing under
.NET 11:

	FocusMovesToNextCorrectElementWhenFocusCandidateElementCollapsed
	System.PlatformNotSupportedException: Operation is not supported on this platform.
	   at System.Runtime.CompilerServices.RuntimeFeature.ThrowIfMultithreadingIsNotSupported()
	   at System.Threading.Tasks.Task.InternalWaitCore(Int32 millisecondsTimeout, CancellationToken cancellationToken)
	   at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
	   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
	   at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)
	   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
	   at Microsoft.UI.Xaml.Tests.Common.EventTester`2[[Microsoft.UI.Xaml.UIElement, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null],[Microsoft.UI.Xaml.RoutedEventArgs, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]]..ctor(UIElement sender, Type senderType, String eventName, Action`2 action, EventTesterOptions options, Boolean setBVTflags)
	   at Microsoft.UI.Xaml.Tests.Common.EventTester`2[[Microsoft.UI.Xaml.UIElement, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null],[Microsoft.UI.Xaml.RoutedEventArgs, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]]..ctor(UIElement sender, Type senderType, String eventName, Action`2 action, EventTesterOptions options)
	   at Microsoft.UI.Xaml.Tests.Common.EventTester`2[[Microsoft.UI.Xaml.UIElement, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null],[Microsoft.UI.Xaml.RoutedEventArgs, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]]..ctor(UIElement sender, String eventName, Action`2 action)
	   at Microsoft.UI.Xaml.Tests.Common.EventTester`2[[Microsoft.UI.Xaml.UIElement, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null],[Microsoft.UI.Xaml.RoutedEventArgs, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]]..ctor(UIElement sender, String eventName)
	   at Uno.UI.RuntimeTests.MUX.Input.Focus.FocusHelper.EnsureFocusAsync(UIElement element, FocusState focusState, UInt32 Attempts)
	   at Uno.UI.RuntimeTests.MUX.Input.Focus.FocusTests.FocusMovesToNextCorrectElementWhenFocusCandidateElementCollapsed()
	   at Uno.UI.Samples.Tests.UnitTestsControl.<>c__DisplayClass74_2.<<ExecuteTestsForInstance>g__InvokeTestMethod|5>d.MoveNext()

This is due to a change within .NET 11, in which
`Task.InternalWaitCore()` was updated to throw
`PlatformNotSupportedException` in wasm environments:

  * https://github.com/dotnet/runtime/commit/a118808de36ec1363536a5a1606b973b7060cd12
  * https://github.com/dotnet/runtime/commit/25eb60e95bb01ec0030f1fe8ee4ee9753412cdcf

The "offending" `Task.Wait()` invocation was *already* wrapped within
`!__WASM__` blocks, but these don't apply within
`SamplesApp.Skia.WebAssembly.Browser`, as that uses *Skia* build
variants of e.g. Uno.UI.RuntimeTests, not Wasm build variants.

Update `EventTester.cs` to add an additional runtime check before
the `Task.Wait()` invocations when running within a browser:

	// old and busted
	#if !__WASM__
	  task.Wait();
	#endif

	// new hawtness
	#if !__WASM__
	  if (!ConditionalTestHelper.CurrentPlatform.HasFlag(RuntimeTestPlatforms.SkiaWasm))
	  {
	    task.Wait();
	  }
	#endif

This allows the `Task.Wait()` invocation to be avoided within a browser
environment, allowing the tests to pass.