chore: Uno.WinUI.Graphics2DSK.nuspec only targets .NET 9 Windows
Context: b789db7f0a58cd900dffc831a75e94cec8ef3b52

Commit b789db7f tried to fix **Build - Managed Binaries**, but failed:

	  Attempting to build package from 'Uno.WinUI.Graphics2DSK.nuspec'.
	  Could not find a part of the path 'C:\a\1\s\src\AddIns\Uno.WinUI.Graphics2DSK\bin\Release\net10.0-windows10.0.19041.0'.
	  System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\a\1\s\src\AddIns\Uno.WinUI.Graphics2DSK\bin\Release\net10.0-windows10.0.19041.0'.
	     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
	     …
	C:\a\1\s\Build\Uno.UI.Build.csproj(355,3): error MSB3073: The command ".\external\nuget\NuGet.exe pack nuget\Uno.WinUI.Graphics2DSK.nuspec -Verbosity Detailed -Version "6.2.0-dev.156.g094e6f1fa9" -Properties "NoWarn=NU5100,NU5105,NU5131;NU5123;branch=094e6f1fa9dc5606d8aea64265ec1800fd1fef4d;commitid=094e6f1fa9dc5606d8aea64265ec1800fd1fef4d;winuisourcepath=net9.0-windows10.0.19041.0;winuitargetpath=net9.0-windows10.0.19041.0"" exited with code 1.

Reviewing `src/AddIns/Uno.WinUI.Graphics2DSK/Uno.WinUI.Graphics2DSK.Windows.csproj`,
and it *only* builds for `$(NetPreviousWinAppSDK)`, i.e. .NET 9 now.

Update `build/nuget/Uno.WinUI.Graphics2DSK.nuspec` so that it doesn't
attempt to package net10.0-windows10\* binaries.