chore: fix C# CS0234 compilation errors
Context: https://github.com/dotnet/sdk/issues/48949
Context: https://github.com/dotnet/android/commit/70bd636b04ebf9dba36c632cdec586452e98cb8a

Commit dotnet/android@70bd636b introduced a "source break", as it
introduced a `Microsoft.Android.Runtime` namespace, which means that
any source code that is *also* in a `Microsoft.` namespace can now
see ambiguity errors:

	src/Uno.UI/UI/Xaml/NativeApplication.cs(23,43): error CS0234: The type or namespace name 'App' does not exist in the namespace 'Microsoft.Android' (are you missing an assembly reference?)
	src/Uno.UI/UI/Xaml/NativeApplication.cs(41,89): error CS0234: The type or namespace name 'JniHandleOwnership' does not exist in the namespace 'Microsoft.Android.Runtime' (are you missing an assembly reference?)
	src/Uno.UI/UI/Xaml/NativeApplication.cs(160,55): error CS0246: The type or namespace name 'IActivityLifecycleCallbacks' could not be found (are you missing a using directive or an assembly reference?)
	…

Fix these by adding `using Android.…` namespace declarations or
`using ATypeName = …` aliases.