feat: Use C# 8.0 by default
BREAKING CHANGE: Uno is now built using VS2019 16.4

It does not support building Xamarin iOS/Android applications with Visual Studio 2017.

Linker errors may occur such as:
```
Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'System.Collections.Generic.Queue`1'
(defined in assembly 'Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null') with scope 'mscorlib, Version=2.0.5.0,
Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
```