chore: fix IL207x warnings in Uno.Foundation
From the **Build - Managed Binaries** stage:

	C:\a\1\s\src\Uno.Foundation\Metadata\ApiInformation.cs(104,5): error IL2075: 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties' in call to 'System.Type.GetProperty(String)'. The return value of method 'Windows.Foundation.Metadata.ApiInformation.GetValidType(String)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
	C:\a\1\s\src\Uno.Foundation\Metadata\ApiInformation.cs(67,5): error IL2075: 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods' in call to 'System.Type.GetMethods()'. The return value of method 'Windows.Foundation.Metadata.ApiInformation.GetValidType(String)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
	C:\a\1\s\src\Uno.Foundation\Metadata\ApiInformation.cs(71,30): error IL2070: 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicEvents' in call to 'System.Type.GetEvent(String)'. The parameter 'type' of method 'Windows.Foundation.Metadata.ApiInformation.IsEventPresent(Type, String)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
	C:\a\1\s\src\Uno.Foundation\Metadata\ApiInformation.cs(76,5): error IL2075: 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicEvents' in call to 'System.Type.GetEvent(String)'. The return value of method 'Windows.Foundation.Metadata.ApiInformation.GetValidType(String)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
	C:\a\1\s\src\Uno.Foundation\Metadata\ApiInformation.cs(91,5): error IL2075: 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties' in call to 'System.Type.GetProperty(String)'. The return value of method 'Windows.Foundation.Metadata.ApiInformation.GetValidType(String)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.

Fix these by sprinkling magic `[DynamicallyAccessedMembers(…)]`
pixie-dust in the appropriate locations.  In particular, on all
`string typeName` or `Type type` parameters, and a new
`[return: DynamicallyAccessedMembers(…)]` on `GetValidType()`.

Add a nested `AssemblyGetType()` method so we can "patch up"
the `[DynamicallyAccessedMembers]` differences between
`GetValidType()` and `Assembly.GetType()`.