chore: fix Android+Native AOT Samples App build
The **Tests - Andorid+NativeAOT Skia** stage was failing:

	/home/AzDevOps/.nuget/packages/microsoft.dotnet.ilcompiler/10.0.5/build/Microsoft.NETCore.Native.targets(330,5): error MSB3073: The command ""/home/AzDevOps/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/10.0.5/tools/ilc" @"obj/Release/net10.0-android/android-arm64/native/SamplesApp.ilc.rsp"" exited with code -1. [/agent/_work/1/s/src/SamplesApp/SamplesApp.Skia.netcoremobile/SamplesApp.Skia.netcoremobile.csproj::TargetFramework=net10.0-android]
	/home/AzDevOps/.nuget/packages/microsoft.dotnet.ilcompiler/10.0.5/build/Microsoft.NETCore.Native.targets(330,5): error MSB3073: The command ""/home/AzDevOps/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/10.0.5/tools/ilc" @"obj/Release/net10.0-android/android-x64/native/SamplesApp.ilc.rsp"" exited with code -1. [/agent/_work/1/s/src/SamplesApp/SamplesApp.Skia.netcoremobile/SamplesApp.Skia.netcoremobile.csproj::TargetFramework=net10.0-android]

In a "is this a good or bad idea" mement, add trimmer annotations to
`IValueConverter`.  This in turn requires *half the universe* to be
updated to have matching annotations.

Do it anyways.  (Wee!)

Additionally, **Tests - iOS Native > … > Build Samples App** failed:

	…/src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs(829,7): error IL2067: 'type' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors', 'DynamicallyAccessedMemberTypes.PublicFields', 'DynamicallyAccessedMemberTypes.PublicProperties' in call to 'SampleControl.Presentation.SampleChooserViewModel.GetContent(Type, SampleAttribute)'. The parameter 'type' of method 'SampleControl.Presentation.SampleChooserViewModel.GetContent(Type)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [/Users/runner/work/1/s/src/SamplesApp/SamplesApp.netcoremobile/SamplesApp.netcoremobile.csproj::TargetFramework=net10.0-ios]
	…/src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs(812,19): error IL2077: 'type' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors', 'DynamicallyAccessedMemberTypes.PublicFields', 'DynamicallyAccessedMemberTypes.PublicProperties' in call to 'SampleControl.Presentation.SampleChooserViewModel.GetContent(Type, SampleAttribute)'. The field '(System.Type type, Uno.UI.Samples.Controls.SampleAttribute sampleAttribute).type' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [/Users/runner/work/1/s/src/SamplesApp/SamplesApp.netcoremobile/SamplesApp.netcoremobile.csproj::TargetFramework=net10.0-ios]

Fixup `SampleChooserViewModel.cs` to address the warnings, and also
re-enable many `[UnconditionalSuppressMessage]` annotations which were
previously removed in 03c71f6a7bc94f9b47518c1a5b58e4b92f47f7eb;
apparently they *are* needed!