chore: Fix Given_WebView2.When_LocalFolder_File()
Context: 4d84ee31adb3e7ecd3fcbdc248b79fee78211d3e
Context: https://github.com/dotnet/java-interop/issues/1260
Context: https://github.com/dotnet/maui/commit/70fbb835d74b7dd6268bfa51ba8f450d0bea22dd
Context: https://github.com/dotnet/maui/commit/b1113d56866e4f41e0bb5b2be2d4c435a04630da

The `Given_WebView2.When_LocalFolder_File()` test was failing:

	Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Timed out waiting for condition to be met. When_LocalFolder_File():344
	  at Private.Infrastructure.TestServices.WindowHelper.WaitFor(Func1 condition, Int32 timeoutMS, String message, String callerMemberName, Int32 lineNumber)
	  at Uno.UI.RuntimeTests.Tests.Microsoft_UI_Xaml_Controls.Given_WebView2.<When_LocalFolder_File>g__Do|7_0()
	  at Uno.UI.RuntimeTests.Helpers.TestHelper.RetryAssert(Func`1 assertion, Int32 count)
	  at Uno.UI.RuntimeTests.Tests.Microsoft_UI_Xaml_Controls.Given_WebView2.When_LocalFolder_File()

The timeout confused me for a bit: why would it be timing out?

`Given_WebView2.cs:344` provided more context:

	webView.NavigationCompleted += (sender, e) => navigated = true;
	…
	await TestServices.WindowHelper.WaitFor(() => navigated, 3000);

`TestServices.WindowHelper.WaitFor()` was timing out, because
`navigated` was never set, because the `webView.NavigationCompleted`
event was never raised.

`webView.NavigationCompleted`, meanwhile, is impacted by the removal
of `[Export]` on `UnoWebViewHandler.PostMessage()` in 4d84ee31!
Now things are making sense!

It turns out that dotnet/maui@70fbb835 did not work, because of
dotnet/java-interop#1260: the .NET for Android Java Callable Wrapper
generator does not process custom attributes on interface method
implementations.

Consequently, this:

	// Java
	public interface UnoWebViewHandlerJavascriptInterface {
	  void postMessage(String message);
	}

	// C#
	class UnoWebViewHandler : Java.Lang.Object, IUnoWebViewHandlerJavascriptInterface {
	  [JavascriptInterface]
	  public void PostMessage(string? message) => …
	}

***Did not work***, as the resulting Java Callable Wrapper for
`UnoWebViewHandler` did not have `@android.webkit.JavascriptInterface`.

The fix for MAUI was in dotnet/maui@b1113d56: use a *`class`*, not an
interface:

	// Java
	public abstract class UnoWebViewHandlerJavascriptInterface {
	  public abstract void postMessage(String message);
	}

	// C#
	class UnoWebViewHandler : UnoWebViewHandlerJavascriptInterface {
	  [JavascriptInterface]
	  public override void PostMessage(string? message) => …
	}

*This* causes the resulting Java Callable Wrapper to have the
necessary `@JavascriptInterface` annotation.

This in turn fixes the `Given_WebView2.When_LocalFolder_File()` test.