chore: fix WinAppSDK Sync Generator Check
The **Restore sync generator solution filter** step was failing:

	Error: C:\Program Files\dotnet\sdk\10.0.105\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(184,5):
	error NETSDK1045: The current .NET SDK does not support targeting .NET 11.0.
	  Either target .NET 10.0 or lower, or use a version of the .NET SDK that supports .NET 11.0.
	  Download the .NET SDK from https://aka.ms/dotnet/download
	  [D:\a\uno\uno\src\Uno.Foundation\Uno.Foundation.Reference.csproj::TargetFramework=net11.0]

Update `winappsdk-sync-apply.yml` et al to use
`build/ci/net11/_global.json` so that .NET 11 is provisioned.

Once that's fixed, we get two additional NuGet errors:

	src/Uno.WinAppSDKSyncGenerator/Uno.WinAppSDKSyncGenerator.csproj : error NU1903: Warning As Error: Package 'System.Security.Cryptography.Xml' 10.0.4 has a known high severity vulnerability, https://github.com/advisories/GHSA-37gx-xxp4-5rgx
	src/Uno.WinAppSDKSyncGenerator/Uno.WinAppSDKSyncGenerator.csproj : error NU1903: Warning As Error: Package 'System.Security.Cryptography.Xml' 10.0.4 has a known high severity vulnerability, https://github.com/advisories/GHSA-w3x6-4m5h-cxqf
	src/Uno.WinAppSDKSyncGenerator/Uno.WinAppSDKSyncGenerator.csproj : error NU1605:
	  Warning As Error: Detected package downgrade: Microsoft.CodeAnalysis.VisualBasic.Workspaces from 4.14.0 to 4.11.0. Reference the package directly from the project to select a different version.
	   Uno.WinAppSDKSyncGenerator -> Microsoft.CodeAnalysis 4.14.0 -> Microsoft.CodeAnalysis.VisualBasic.Workspaces (= 4.14.0)
	   Uno.WinAppSDKSyncGenerator -> Microsoft.CodeAnalysis.VisualBasic.Workspaces (>= 4.11.0)

Fix the NU1605 by setting `$(SyncGeneratorCodeAnalysisVersion)`=4.14.0.

Fix the NU1903 by *adding* a package reference to
`System.Security.Cryptography.Xml` 10.0.9, which is the current latest
non-preview version of the package.