chore: Preserve properties on types referenced in XAML
Fixes: https://github.com/unoplatform/uno-private/issues/1795

Context: 559b1f7866028a1d23f74ba43c3e8614a8e9f284

What do we want?  Native AOT support which requires a *minimum* of
app changes.

Enter our test case: [unoplatform/Uno.Gallery][0].  There is a draft
[PR to add Native AOT support to Uno.Gallery][1], but it requires a
number of changes to app code, largely by adding `[Bindable]` to
types so that their properties can be accessed via XAML.

We would prefer that such changes *not* be required.

Enter one failing sample: if we build and run the Uno.Gallery
Native AOT PR and remove the `[Bindable]` changes for macOS:

	git clone https://github.com/unoplatform/Uno.Gallery
	cd Uno.Gallery
	git checkout dev/jonpryor/jonp-naot-support
	# remove all additions of [Bindable]
	for f in `git grep -l Bindable`; do git checkout -f HEAD^ $f ; done
	# use  Uno.Sdk 6.6.0-dev.122 which includes the fix for uno-private#1735 and also MVVM fixes…
	sed -i '' 's/"Uno.Sdk": ".*"/"Uno.Sdk": "6.6.0-dev.122"/g' global.json
	dotnet publish -r osx-x64 -f net10.0-desktop -p:TargetFrameworkOverride=net10.0-desktop -p:SkiaPublishAot=true -bl Uno.Gallery/Uno.Gallery.csproj \
	  -p:EmitCompilerGeneratedFiles=true -p:CompilerGeneratedFilesOutputPath=`pwd`/_gen
	./Uno.Gallery/bin/Release/net10.0-desktop/osx-x64/publish/Uno.Gallery

After running the app, navigate to **UI features > Bindable**, and
in the *myTextBox* field enter `1234`.

Expected results: the **The text of myTextBox is:** and
**The length is** fields are updated accordingly.

Actual results: no changes at all!

![Text is entered, but bound fields are not updated][2]

App output contains:

	fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
	      The [Text] property getter does not exist on type [Uno.Gallery.Views.Samples.BindingSamplePageViewModel]
	fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
	      The [Text] property getter does not exist on type [Uno.Gallery.Views.Samples.BindingSamplePageViewModel]
	fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
	      The [TextLength] property getter does not exist on type [Uno.Gallery.Views.Samples.BindingSamplePageViewModel]
	fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
	      The [TextLength] property getter does not exist on type [Uno.Gallery.Views.Samples.BindingSamplePageViewModel]
	fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
	      The property setter for [Text] does not exist on [Uno.Gallery.Views.Samples.BindingSamplePageViewModel]

The problem is that [`BindingSamplePage.xaml`][3] references the
``BindingSamplePageViewModel` type:

	<StackPanel.DataContext>
	  <samples:BindingSamplePageViewModel />
	</StackPanel.DataContext>

and then uses properties on `BindingSamplePageViewModel`, e.g.

	<Run Text="{Binding Text}" />

but nothing in the project causes the `BindingSamplePageViewModel`
properties to be added to reflection metadata (559b1f78).

*However*, due to `<StackPanel.DataContext/>`, the
`BindingSamplePageViewModel` type *is mentioned* in the generated
code-behind:

	namespace Uno.Gallery.Views.Samples {
	  partial class BindingSamplePage : global::Microsoft.UI.Xaml.Controls.Page {
	    private partial class __BindingSamplePage_7ce649f821654d6be1d08e2804c16477 {
	      public class __PagΞ0_GriΞ0_SamPagLay_DesAgnTemΞ0_DatTem {
	        public _View Build(object __ResourceOwner_1, global::Microsoft.UI.Xaml.TemplateMaterializationSettings __settings)
	        {
	          // …
	          new global::ShowMeTheXAML.XamlDisplay {
	            IsParsing = true,
	            UniqueKey = "BindingSamplePage_Binding",
	            // Source ../../../../Views/SamplePages/BindingSamplePage.xaml (Line 17:7)
	            Content = new global::Microsoft.UI.Xaml.Controls.StackPanel {
	              IsParsing = true,
	              DataContext = new global::Uno.Gallery.Views.Samples.BindingSamplePageViewModel

What If™ we could update that `new BindingSamplePageViewModel`
expression so that properties for `BindingSamplePageViewModel` are
automatically added to reflection metadata?

Update `src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator`
as follows:

  * Update the `GlobalStaticResources` type definition to include the
    following method:

        partial class GlobalStaticResources
        {
          internal static T __PreserveProperties<
            [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicProperties)] T
          >(T value) => value;
        }

  * Update `XamlFileGenerator.BuildChild()` to wrap it's output in a
    call to `GlobalStaticResources.__PreserveProperties()`.

This updates the above `DataContext` assignment to now be:

	DataContext = GlobalStaticResources.__PreserveProperties(
	  new BindingSamplePageViewModel
	  {
	    // Source ../../../../Views/SamplePages/BindingSamplePage.xaml (Line 21:10)
	  }
	)

This in turn causes the properties on `BindingSamplePageViewModel` to
be added to reflection metadata, allowing the **UI features > Binding**
sample to work as intended.

Somewhat unrelated: update
`src/SourceGenerators/Uno.UI.SourceGenerators.Tests` to *begin*
supporting execution on macOS, by using `Path.Combine()` instead of
hardcoding `\` as the path separator.  This fixes errors such as:

	failed TestNested (147ms)
	  from src/SourceGenerators/Uno.UI.SourceGenerators.Tests/bin/Debug/net10.0/Uno.UI.SourceGenerators.Tests.dll (net10.0|x64)
	  Test method Uno.UI.SourceGenerators.Tests.DependencyObjectGeneratorTests.Given_DependencyObjectGenerator.TestNested threw exception:
	  System.InvalidOperationException: Context: Source generator application
	  Context: Verifying source generated files
	  Expected source file list to match
	  -Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.DependencyObject.DependencyObjectGenerator\OuterClass.Inner.cs
	  +Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.DependencyObject.DependencyObjectGenerator/OuterClass.Inner.cs

[0]: https://github.com/unoplatform/Uno.Gallery/
[1]: https://github.com/unoplatform/Uno.Gallery/pull/1233
[2]: https://private-user-images.githubusercontent.com/155958/560918773-b4d26197-91e8-4e12-9961-19f4fed470c3.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzMxNDYwNTAsIm5iZiI6MTc3MzE0NTc1MCwicGF0aCI6Ii8xNTU5NTgvNTYwOTE4NzczLWI0ZDI2MTk3LTkxZTgtNGUxMi05OTYxLTE5ZjRmZWQ0NzBjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDMxMFQxMjI5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTVjMDc3NGQ4OTI4MWIwZWRiYzU2NjZiZTYyMTIyOWMzMWUwYTE4YTQwMzE0NWYyYTc1YTg4Yjg3NTAzM2E5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jflukIo_4sL2P9xOeyR5moZRPJifP0VK6Z32TcPWgaU
[3]: https://github.com/unoplatform/Uno.Gallery/blob/5fc5329679c78472d7589df581e6cc712f3277da/Uno.Gallery/Views/SamplePages/BindingSamplePage.xaml