chore(deps): Update Uno.Wasm.Bootstrap to 10.0.0-dev.24
The **Tests - WebAssembly Skia > Run Runtime Tests \* > Run WebAssembly Skia Runtime Tests**
job fails with:

	Error: Failed to load config file blazor.boot.json SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
	    at xe (http://localhost:8000/_framework/dotnet.js:4:21471)
	    at async http://localhost:8000/_framework/dotnet.js:4:31096
	    at async Bootstrapper.bootstrap (http://localhost:8000/package_cad083c022126debd2f8488f4d32c39d75cb8f7b/uno-bootstrap.js:159:47)", source: http://localhost:8000/_framework/dotnet.js (4)

This is because we need to use a newer version of the
Uno.Wasm.Bootstrap NuGet package.

Update `NuGet.config` so that we can find the Uno.Wasm.Bootstrap
NuGet package version 10.0.0-dev.24, and update
`Directory.Build.targets` to use 10.0.0-dev.24 instead of 9.0.16.