chore: Update to .NET 11 rc.1
Context: https://github.com/unoplatform/uno/issues/22745
Context: https://github.com/dotnet/android/pull/12750
Context: https://github.com/dotnet/runtime/issues/133911
Context: f42da0432d86bc5fc664cfc724221421744c9530

Update version numbers accordingly.

To sanity-check locally, try:

	\cp build/ci/net11/_global.json global.json

	dotnet build -f net11.0-ios26.5 src/Uno.Foundation/Uno.Foundation.netcoremobile.csproj
	dotnet build -f net11.0 src/Uno.UI/Uno.UI.csproj
	dotnet publish -f net11.0-android -p:UnoTargetFrameworkOverride=net11.0-android src/SamplesApp/SamplesApp/SamplesApp.csproj -p:UNO_DISABLE_ANALYZERS_IN_SAMPLES=true
	dotnet publish -f net11.0-android -p:UnoTargetFrameworkOverride=net11.0-android src/SamplesApp/SamplesApp/SamplesApp.csproj -p:ApplicationId=uno.platform.samplesapp.skia.nativeaot -p:SkiaPublishAot=true -p:SkiaSharpVersion=4.151.1
	dotnet build -c Release -f net11.0-ios -p:UnoTargetFrameworkOverride=net11.0-ios src/SamplesApp/SamplesApp/SamplesApp.csproj

Note: when updating `_Dotnet.cs`, the `version` value in
`new PackageIdentity(id, version)` must match the *filesystem path*
underneath `packs/Microsoft.NETCore.App.Ref`, which *may not* match
the output of `dotnet --version`.  Check the filesystem!

Address an IL2080 trimmer warning:

	// 249: var (methodName, type) = OperatingSystem.IsBrowser() ? ($"uno_{typeof(T).Name}", typeof(BrowserICUSymbols)) : ($"{typeof(T).Name}_{_icuVersion}", typeof(IOSICUSymbols))
	src/Uno.UI/UI/Xaml/Documents/UnicodeText.ICU.cs(249,19): error IL2080: 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.NonPublicMethods' in call to 'System.Type.GetMethod(String, BindingFlags)'. The field '(System.String, System.Type).Item2' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.

Filed dotnet/runtime#133911 for the above warning, as it feels wrong.

Note: Android+NativeAOT *still* fails to build by default, due to a
similar bug as in .NET 11 Preview 7; see also f42da043, e.g.

	Unable to find package Microsoft.NETCore.App.Runtime.NativeAOT.android-arm64 with version (= 11.0.0-rc.1.26428.117)
	  - Found 23 version(s) in nuget.org [ Nearest version: 11.0.0-rc.1.26425.128 ]
	  - Found 0 version(s) in /Users/jon/Downloads/dotnet-sdk-11.0.100-rc.1.26425.128/library-packs

Update the workaround within `Uno.CrossTargetting.targets`, and
cross fingers 🤞 that .NET 11 rc.2 doesn't require this workaround.

Update `android-run-skia-runtime-tests.sh` to capture a screenshot of
the device screen as the tests are run, so we can see what is shown
when Android tests hang.

Finally, update `android-run-skia-runtime-tests.sh` and
`android-uitest-run.sh` to *stop* installing the `tools` package.
Attempting to install it is now an error:

	% ($ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=/tmp/my-sdk --install 'tools') ; echo exit=$?
	Warning: Failed to find package 'tools'
	[===                                    ] 10% Computing updates...
	exit=1

(The `tools` package was last updated in *2017-September*, has been
deprecarted for quite some time, and is now no longer mentioned in
[`repository2-3.xml`][0], which lists all Android SDK packages.
This removal has been a long time coming…)

[0]: https://dl.google.com/android/repository/repository2-3.xml