chore: fix build break in Build - Managed Binaries
	src\Uno.UI.XamlHost.Skia.Wpf\UnoXamlHostWrapperConverter.cs(20,40): error CS0246: The type or namespace name 'DynamicallyAccessedMembersAttribute' could not be found (are you missing a using directive or an assembly reference?) [D:\a\1\s\src\Uno.UI.XamlHost.Skia.Wpf\Uno.UI.XamlHost.Skia.Wpf.csproj::TargetFramework=net10.0-windows]
	src\Uno.UI.XamlHost.Skia.Wpf\UnoXamlHostWrapperConverter.cs(20,40): error CS0246: The type or namespace name 'DynamicallyAccessedMembers' could not be found (are you missing a using directive or an assembly reference?) [D:\a\1\s\src\Uno.UI.XamlHost.Skia.Wpf\Uno.UI.XamlHost.Skia.Wpf.csproj::TargetFramework=net10.0-windows]
	src\Uno.UI.XamlHost.Skia.Wpf\UnoXamlHostWrapperConverter.cs(20,83): error CS0117: 'IValueConverter' does not contain a definition for 'TargetTypeRequirements' [D:\a\1\s\src\Uno.UI.XamlHost.Skia.Wpf\Uno.UI.XamlHost.Skia.Wpf.csproj::TargetFramework=net10.0-windows]

The CS0117 at least makes sense: we're not using Uno's IValueConverter.

The CS0246 does *not* make sense, as afaict the project is built against
the .NET 10 `System.Runtime.dll`, which *should* contain
`DynamicallyAccessedMembersAttribute`.

Let's see if `DynamicallyAccessedMemberTypes` is resolved…