chore: support Linux + Framebuffer devices
Recall "chore: avoid Task.Wait() on SkiaWasm"?  In which
`EventTester.cs` was updated to avoid `Task.Wait()` invocations on
WebAssembly + Skia ("SkiaWasm"), and did this by updating
`ConditionalTestHelper.CurrentPlatform`?

That change breaks on "Desktop Skia Linux" and
"Desktop Skia Linux Framebuffer"

	System.InvalidOperationException: Unrecognized runtime platform.
	   at Microsoft.VisualStudio.TestTools.UnitTesting.ConditionalTestHelper.GetCurrentPlatform() in D:\a\1\s\src\Uno.UI.RuntimeTests\Helpers\ConditionalTestHelper.cs:line 28
	   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
	--- End of stack trace from previous location ---
	   at System.LazyHelper.ThrowException()
	   at System.Lazy`1.CreateValue()
	   at System.Lazy`1.get_Value()
	   at Microsoft.VisualStudio.TestTools.UnitTesting.ConditionalTestHelper.get_CurrentPlatform() in D:\a\1\s\src\Uno.UI.RuntimeTests\Helpers\ConditionalTestHelper.cs:line 10
	   at Microsoft.UI.Xaml.Tests.Common.EventTester`2..ctor(TSender sender, Type senderType, String eventName, Action`2 action, EventTesterOptions options, Boolean setBVTflags) in D:\a\1\s\src\Uno.UI.RuntimeTests\MUX\Helpers\EventTester.cs:line 113
	   at Microsoft.UI.Xaml.Tests.Common.EventTester`2..ctor(TSender sender, Type senderType, String eventName, Action`2 action, EventTesterOptions options) in D:\a\1\s\src\Uno.UI.RuntimeTests\MUX\Helpers\EventTester.cs:line 143
	   at Microsoft.UI.Xaml.Tests.Common.EventTester`2..ctor(TSender sender, String eventName, Action`2 action) in D:\a\1\s\src\Uno.UI.RuntimeTests\MUX\Helpers\EventTester.cs:line 160
	   at Microsoft.UI.Xaml.Tests.Common.EventTester`2..ctor(TSender sender, String eventName) in D:\a\1\s\src\Uno.UI.RuntimeTests\MUX\Helpers\EventTester.cs:line 179
	   at Uno.UI.RuntimeTests.MUX.Input.Focus.FocusHelper.EnsureFocusAsync(UIElement element, FocusState focusState, UInt32 Attempts) in D:\a\1\s\src\Uno.UI.RuntimeTests\MUX\Input\Focus\FocusHelper.cs:line 77
	   at Uno.UI.RuntimeTests.MUX.Input.Focus.FocusTests.ElementMovesToCorrectElementWhenFocusedElementCollapsed() in D:\a\1\s\src\Uno.UI.RuntimeTests\MUX\Input\Focus\FocusTests.cs:line 1403
	   at Uno.UI.Samples.Tests.UnitTestsControl.<>c__DisplayClass74_2.<<ExecuteTestsForInstance>g__InvokeTestMethod|5>d.MoveNext() in D:\a\1\s\src\SamplesApp\SamplesApp.UnitTests.Shared\Controls\UnitTest\UnitTestsControl.cs:line 1035

When discussing appropriate fixes for `EventTester.cs`,
@MartinZikmund suggested that `OperatingSystem.IsBrowser()` be used
instead of updating `ConditionalTestHelper.CurrentPlatform`.
Unfortunately this suggestion came *after* I had already tried updating
`ConditionalTestHelper.CurrentPlatform`, but now that the fix itself
causes problems elsewhere…

Update `EventTester.cs` to use `OperatingSystem.IsBrowser()` instead
of `ConditionalTestHelper.CurrentPlatform`.

Update `ConditionalTestHelper.cs` so that exceptions provide more
information if (when) they throw.