chore: Update to .NET 11 Preview 1
Context: https://github.com/unoplatform/uno/issues/22745
Context? 69cc392740d79597b3f8e1a846d0562732c134ac

Last time when trying to update uno/master to use .NET 10 previews,
the PR was *gigantic*.

Perhaps trying to use .NET 11 previews will grow to be similarly
gigantic, but for starters let's try to keep things manageable:

By default, only .NET 9 and .NET 10 are targeted.

To build for .NET 11, build with `$(UnoEnablePreviewFeatures)`=true,
which alters e.g. `$(NetSkiaPreviousAndCurrent)` to be
`net10.0;net11.0` instead of `net9.0;net10.0`:

	cp build/ci/net11/_global.json global.json
	export PATH=/location/of/net11:$PATH
	dotnet build -p:UnoEnablePreviewFeatures=true -f net11.0 src/Uno.Foundation/Uno.Foundation.csproj
	dotnet build -p:UnoEnablePreviewFeatures=true -f net11.0 src/Uno.UI/Uno.UI.Skia.csproj
	dotnet build -p:UnoEnablePreviewFeatures=true -f net11.0-android src/Uno.UI/Uno.UI.netcoremobile.csproj
	dotnet build -p:UnoEnablePreviewFeatures=true -f net11.0-android src/SamplesApp/SamplesApp.Skia.netcoremobile/SamplesApp.Skia.netcoremobile.csproj

Changes:

  * The C# compiler emits new (to us) CS9336 warnings. Consider:

        // from src/AddIns/Uno.WinUI.SpellChecking/WeCantSpell.Hunspell/FlagValue.cs
        public bool IsNotWildcard => _value is not '*' or '?';

    would trigger:

        error CS9336: The pattern is redundant.

    When using `expr is not` against more than one value, the values
    must be enclosed in parentheses:

        public bool IsNotWildcard => _value is not ('*' or '?');

  * .NET 11 has new IDE0055 warnings for pre-existing constructs;
    in particular, `else if` must be on the same line, and
    `#region`/`#endregion` must have matching indentation.

    Update various files to fix these warnings.

  * Duplicate various `<ItemGroup/>`s to add support for net11.0*.
    (Duplicate instead of update existing item groups so that if in
    the future we need to e.g. change package versions, we can do so
    with minimal noise.)

  * When it makes sense to do so, use `$(NetPrevious)` and
    `$(NetCurrent)` instead of hardcoding target frameworks.