chore: fix Tests - Unit Tests
Commit 49b172df7680b84c43da3df4640702825d6e8ac5 mentioned this failure:

>     failed TestAndroidViewImplementingDependencyObject (819ms)
>       from C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators.Tests\bin\Release\net10.0\Uno.UI.SourceGenerators.Tests.dll (net10.0|x64)
>       Test method Uno.UI.SourceGenerators.Tests.DependencyObjectGeneratorTests.Given_DependencyObjectGenerator.TestAndroidViewImplementingDependencyObject threw exception:
>       System.InvalidOperationException: Mismatch between number of diagnostics returned, expected "1" actual "4"
>
>       Diagnostics:
>       // /0/Test0.cs(6,14): error Uno0003: 'Android.Views.View' shouldn't implement 'DependencyObject'. Inherit 'FrameworkElement' instead.
>       DiagnosticResult.CompilerError("Uno0003").WithSpan(6, 14, 6, 15).WithArguments("Android.Views.View"),
>       // /0/Test0.cs(3,20): error CS0234: The type or namespace name 'Dispatching' does not exist in the namespace 'Microsoft.UI' (are you missing an assembly reference?)
>       DiagnosticResult.CompilerError("CS0234").WithSpan(3, 20, 3, 31).WithArguments("Dispatching", "Microsoft.UI"),
>       // /0/Test0.cs(6,38): error CS0012: The type 'DispatcherQueue' is defined in an assembly that is not referenced. You must add a reference to assembly 'Uno.UI.Dispatching, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'.
>       DiagnosticResult.CompilerError("CS0012").WithSpan(6, 38, 6, 54).WithArguments("Microsoft.UI.Dispatching.DispatcherQueue", "Uno.UI.Dispatching, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null"),
>       // /0/Test0.cs(13,9): error CS0246: The type or namespace name 'DispatcherQueue' could not be found (are you missing a using directive or an assembly reference?)
>       DiagnosticResult.CompilerError("CS0246").WithSpan(13, 9, 13, 24).WithArguments("DispatcherQueue"),
>
> This is *presumably* because some assembly references are missing
> or not resolved.  What *is* being resolved?  Try to printf-debug this.

Results were very useful:

	# jonp: Given_DependencyObjectGenerator.TestAndroid: AdditionalReferences=
		C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators.Tests\bin\Release\net10.0\..\..\..\..\..\Uno.UI\bin\Uno.UI.Reference\Release\net9.0\Uno.UI.dll
		C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators.Tests\bin\Release\net10.0\..\..\..\..\..\Uno.UWP\bin\Uno.Reference\Release\net9.0\Uno.dll
		C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators.Tests\bin\Release\net10.0\..\..\..\..\..\Uno.Foundation\bin\Uno.Foundation.Reference\Release\net9.0\Uno.Foundation.dll
		C:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators.Tests\bin\Release\net10.0\..\..\..\..\..\Uno.UI.Composition\bin\Uno.UI.Composition.Reference\Release\net9.0\Uno.UI.Composition.dll

As guessed, there was no assembly reference for `Uno.UI.Dispatching.dll`,
required to resolve `Microsoft.UI.Dispatching`.

After nuking and rebuilding my local tree, I was able to repro, and
found that the "problem" is that while I had
`src\Uno.UI\bin\Uno.UI.Tests\Release\net10.0\Uno.UI.Dispatching.dll`,
it wasn't found because `…\net9.0\…` directories were checked for and
used *first*.

Update `UnoAssemblyHelper.GetBinDirectory()` so that the "target" is
more important than "tfm".  Consider:

	..LoadAssemblies(GetBinDirectory(
		"Uno.UI",
		"Uno.UI.dll",
		[
			// On CI the test assemblies set must be first, as it contains all dependent assemblies
			"Uno.UI.Tests",
			"Uno.UI.Skia",
			"Uno.UI.Reference",
		],
		[TFMPrevious, TFMCurrent]
	)),

Previously, this would look for:

  * `src\Uno.UI\bin\Uno.UI.Tests\Release\net9.0\Uno.UI.dll`
  * `src\Uno.UI\bin\Uno.UI.Skia\Release\net9.0\Uno.UI.dll`
  * `src\Uno.UI\bin\Uno.UI.Reference\Release\net9.0\Uno.UI.dll`
  * `src\Uno.UI\bin\Uno.UI.Tests\Release\net10.0\Uno.UI.dll`
  * `src\Uno.UI\bin\Uno.UI.Skia\Release\net10.0\Uno.UI.dll`
  * `src\Uno.UI\bin\Uno.UI.Reference\Release\net10.0\Uno.UI.dll`

and use first the directory that succeeded.

However, presumably because of bumping `$(NetUnitTests)`=net10.0,
`src\Uno.UI\bin\Uno.UI.Tests\Release\net9.0\Uno.UI.dll` doesn't exist.
`src\Uno.UI\bin\Uno.UI.Tests\Release\net10.0\Uno.UI.dll` *does* -- as
does `src\Uno.UI\bin\Uno.UI.Tests\Release\net10.0\Uno.UI.Dispatching.dll` --
but because `…\Uno.UI.Tests\…\net9.0` didn't exist, `GetBinDirectory()`
would move on to check `…\Uno.UI.Skia\…\net9.0\Uno.UI.dll` (doesn't exist)
and then `…\Uno.UI.Reference\…\net9.0\Uno.UI.dll`, which *does* exist,
but there wasn't a `…\Uno.UI.Skia\…\net9.0\Uno.UI.Dispatching.dll`.

Update `GetBinDirectory()` so that the *target* is more important
than the tfm, resulting in *this* search order:

  * `src\Uno.UI\bin\Uno.UI.Tests\Release\net9.0\Uno.UI.dll`
  * `src\Uno.UI\bin\Uno.UI.Tests\Release\net10.0\Uno.UI.dll`
  * `src\Uno.UI\bin\Uno.UI.Skia\Release\net9.0\Uno.UI.dll`
  * `src\Uno.UI\bin\Uno.UI.Skia\Release\net10.0\Uno.UI.dll`
  * `src\Uno.UI\bin\Uno.UI.Reference\Release\net9.0\Uno.UI.dll`
  * `src\Uno.UI\bin\Uno.UI.Reference\Release\net10.0\Uno.UI.dll`

This allows `…\Uno.UI.Tests\…\net10.0` to be used,, which *does* have
a `…\Uno.UI.Tests\…\net10.0\Uno.UI.Dispatching.dll`, which fixes the
CS0012 and related errors.

Yay.

But wait that's not enough. Trying *just* that change results in
additional errors:

	// error CS1705: Assembly 'Uno' with identity 'Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' uses 'System.Runtime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

This is because the reference assemblies used are
`_Dotnet.Current.ReferenceAssemblies`, which were for *.NET 9*:

	record partial class _Dotnet {
	  public static _Dotnet Current = new("net10.0", ReferenceAssemblies.Net.Net90);
	}

@jonpryor doesn't understand the intent here: why is "net10.0" using
the *net9.0" reference assemblies?

Bump to `Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing` 1.1.3
(which references `Microsoft.CodeAnalysis.Analyzer.Testing`) to use
`ReferenceAssemblies.Net.Net100`:

	record partial class _Dotnet {
	  public static _Dotnet Current = new("net10.0", ReferenceAssemblies.Net.Net100);
	}

This allows the .NET 10 reference assemblies to be used, fixing the
CS1705 errors, and allowing the tests to pass.